/* English legal content — AI translation of the Hebrew source, PENDING HUMAN LEGAL REVIEW. Faithful translation; Israeli law governs. Structure mirrors legalContent.js. */
import { PRIVACY_VERSION, DPA_VERSION, TERMS_VERSION } from '../../lib/legal'

export const PRIVACY_META = `Simplicity · Version ${PRIVACY_VERSION} · Beta · Updated: June 2026`
export const TERMS_META = `Simplicity · Version ${TERMS_VERSION} · Beta · Updated: June 2026`
export const DPA_META = `Data Processing Agreement · Version ${DPA_VERSION} · June 2026`

export const PRIVACY_BLOCKS = [
  { h: "1. Introduction" },
  { t: "Simplicity (the \"Service\", the \"Application\") is a Practice OS (practice-management system) intended for coaches, mentors, and therapists. The Service is operated by Benaya Dor (\"we\", the \"Operator\")." },
  { t: "This Privacy Policy explains what data is collected, how it is processed and stored, what your rights are, and how to contact us. The policy was drafted in accordance with the Protection of Privacy Law, 5741-1981 and its regulations (including Amendment 13), and with the GDPR where relevant." },
  { t: "Use of the Service constitutes consent to the terms set out in this policy. If you do not agree — please discontinue use." },

  { h: "2. Key Definitions" },
  { t: "User — a coach, mentor, or therapist who registers for the Service and uses it to manage their practice." },
  { t: "End client — the person whom the User supports, and whose details are entered into the Application by the User. An end client is not a direct party to any agreement with Simplicity." },
  { t: "User data — any information created, entered, or synced to the Service by the User." },
  { t: "Operator — Benaya Dor, exempt dealer (עוסק פטור, an Israeli small-business tax status), Israel. Email: simplicity.os.app@gmail.com" },

  { h: "3. Relationship Between the Parties — Controller and Processor" },
  { t: "With respect to end-client data: the User is the \"data controller (Controller)\" — the party that decides what to collect and why. Simplicity is the \"data processor (Processor)\" — it processes the data solely in accordance with the User's instructions and for the purpose of providing the Service." },
  { t: "With respect to the User's own data (account, profile, usage data): Simplicity is the data controller (Controller)." },
  { t: "Responsibility for obtaining informed consents from end clients, for the lawfulness of collecting information about them, and for its accuracy, rests entirely with the business User alone. The Operator shall not bear any liability toward third parties whose data was entered into the system by the User." },

  { h: "4. Data Collected" },
  { h2: "4.1 User data" },
  { t: "Full name, email address, encrypted password (or Google authentication) — upon registration." },
  { t: "Profession/role — for personalizing the interface." },
  { t: "Usage data — general activity for operating and improving the Service." },
  { h2: "4.2 End-client data (entered by the User)" },
  { t: "The User manually enters data about their end clients. Such data may include:" },
  { t: "Full name, phone, email address." },
  { t: "Notes, session summaries, and reflections — these may contain sensitive information." },
  { t: "Financial data — cost per session, payment history." },
  { t: "This data is stored on European Union servers, isolated separately for each User (Row-Level Security — each User accesses only their own data), and protected by at-rest storage encryption at the infrastructure level and by transport encryption (HTTPS/TLS). Limited technical access to the infrastructure exists for operational, support, and backup purposes only." },
  { h2: "4.3 Google Calendar sync (optional)" },
  { t: "If the User chooses to connect their Google Calendar, the Application requests read-only access (calendar.readonly) to the primary calendar. Stored: event title, start and end time, duration. Not stored: description, attendee list, location." },
  { t: "Calendar access tokens are stored securely and restricted to system access only. The calendar can be disconnected at any time — disconnecting revokes the access permission at Google." },
  { h2: "4.4 Technical information and digital identifiers (Amendment 13)" },
  { t: "In accordance with Amendment 13 to the Protection of Privacy Law, technical information such as IP address, location data, and digital identifiers is considered personal information for all intents and purposes, and we treat it with the required level of security and privacy. Information of this kind is collected in a limited manner for operating and securing the Service only." },
  { h2: "4.5 Voluntariness of providing the information" },
  { t: "You are under no legal obligation to provide the information; it is provided at your own discretion and with your consent, for the purposes detailed in Section 5. However, without the essential information (such as name and email upon registration) we will not be able to provide the Service." },

  { h: "5. How Data Is Used" },
  { t: "Providing the Service — managing clients, sessions, finances, and goals for the User." },
  { t: "Improving the Service — analyzing anonymous usage patterns for development purposes." },
  { t: "Technical support — handling inquiries and faults." },
  { t: "Security — detecting misuse and preventing unauthorized access." },
  { t: "Simplicity does not sell data and does not share it with advertising entities. We do not use personal information to train artificial-intelligence models, and we do not use the content of notes, summaries, or end-client data to train models of any kind." },

  { h: "6. Data Storage and Security" },
  { h2: "6.1 Storage location" },
  { t: "Service data is stored on Supabase servers in Ireland (eu-west-1 region), within the European Union domain, in accordance with the GDPR." },
  { h2: "6.2 Encryption" },
  { t: "The data is encrypted at rest (at-rest) at the infrastructure level of the hosting provider (Supabase), and isolated for each User via Row-Level Security — so that each User accesses only their own data." },
  { t: "All communication between the Application and the server is encrypted using the HTTPS/TLS protocol." },
  { t: "User passwords are stored in hashed form only (not in plain text)." },
  { h2: "6.3 Internal access" },
  { t: "The Simplicity team has limited technical access to the data infrastructure for operational, support, and backup purposes, restricted to authorized personnel only. We do not sell data, we do not share it with advertisers, and we do not use the content of notes to train models (see Section 5)." },
  { h2: "6.4 Security level and privacy-protection management" },
  { t: "The Service implements security measures in accordance with the Privacy Protection (Information Security) Regulations, 5777-2017, at a medium security level (Level 3): complex password procedures and permission management, logging and monitoring of access to the database (Logs), and periodic security audits." },
  { t: "A Data Protection Officer (DPO) has been appointed, responsible for privacy-protection matters in the organization; they may be contacted at simplicity.os.app@gmail.com." },
  { h2: "6.5 Third-party service providers" },
  { t: "Simplicity uses the following service providers to operate the Service:" },
  { t: "Supabase (Ireland) — database and user authentication." },
  { t: "Vercel (USA) — hosting of the user interface. May process IP data and logs." },
  { t: "Google (USA) — OAuth authentication and calendar sync, subject to Google's privacy policy." },
  { t: "Resend (USA) — sending email messages from the system." },
  { t: "Analytics — future: to be added upon activation of an analytics service. We currently do not use any third-party analytics tools." },
  { t: "These providers are subject to appropriate data processing agreements (DPAs). Information transferred to them is transferred, to the extent possible, in anonymized or coded form." },

  { h: "7. International Data Transfer" },
  { t: "Some of our service providers are located outside Israel (such as Vercel and Google in the USA). Transfer of information to and from European Union countries is carried out in accordance with the Adequacy Decision granted to Israel." },
  { t: "When transferring to countries that do not have an adequate level of protection, we ensure that the transfer is carried out through an appropriate legal mechanism — Standard Contractual Clauses (SCC), the explicit consent of the data subject, or a contractual undertaking by the recipient to comply with the standards of Israeli privacy protection." },

  { h: "8. Data Retention and Deletion" },
  { h2: "8.1 As long as the account is active" },
  { t: "The data is retained as long as the account is active, for the purpose of providing the Service." },
  { h2: "8.2 Account deletion" },
  { t: "The User may delete their account at any time from the Application settings. After a deletion request:" },
  { t: "The request can be canceled within 30 days." },
  { t: "After 30 days — all data is permanently deleted, including end-client data, sessions, notes, and files." },
  { t: "Data cannot be restored after the final deletion." },
  { h2: "8.3 Data export" },
  { t: "The User may export all of their data at any time from the Application settings, in Excel format. The export includes: clients, sessions, notes, transactions, goals, and daily responses — as selected by the User." },

  { h: "9. User Rights" },
  { t: "In accordance with the Protection of Privacy Law (1981) and the GDPR, the User has the following rights:" },
  { t: "Access (Section 13 of the Law) — to request to see what data is stored about them." },
  { t: "Correction (Section 14 of the Law) — to demand correction of information that is incorrect, incomplete, or out of date." },
  { t: "Deletion / the right to be forgotten — to demand deletion of the data (see Section 8.2), subject to exceptions provided by law." },
  { t: "Portability — to export the data in a structured, machine-readable format (see Section 8.3)." },
  { t: "Objection — to object to the processing of data for direct-marketing purposes or in certain other cases." },
  { t: "Prevention of spam (Section 30A of the Communications Law) — promotional mailings will be sent only subject to explicit consent; you may remove yourself from the mailing list at any time, free of charge, via the unsubscribe link at the bottom of each message or by contacting simplicity.os.app@gmail.com." },
  { t: "To exercise these rights: simplicity.os.app@gmail.com — we will respond within 30 days. To protect the information, we will verify the identity of the requester before disclosing, correcting, or deleting data." },

  { h: "10. Use of Data for Marketing Purposes" },
  { t: "Subject to explicit consent upon registration, we may use the User's email address to create tailored advertising audiences (such as Lookalike Audiences) on platforms such as Meta, for the purpose of expanding Simplicity's user base." },
  { t: "This use: is conditional on explicit consent only — not checked by default at registration. Is limited to the User's email only — not end-client data, not notes, not content. Can be revoked at any time — by contacting simplicity.os.app@gmail.com." },
  { t: "A User who has not consented will not be included in any marketing activity of this kind." },

  { h: "11. Cookies and Tracking" },
  { t: "The Application uses technical cookies necessary for its operation (saving login state). These cookies are exempt from consent." },
  { t: "Subject to your consent — given through the cookie banner on the site — we may also use analytics and advertising cookies, including cookies for usage measurement, showing relevant ads, and retargeting landing-page visitors. These non-essential cookies are not loaded until you consent, and you can refuse or withdraw your consent at any time through the banner." },
  { t: "The Application's fonts are loaded from Google Fonts — this action exposes the User's IP address to Google's servers. No additional information is collected." },

  { h: "12. Notification of a Security Incident" },
  { t: "In accordance with the Privacy Protection (Information Security) Regulations, 5777-2017, in the event of a severe security incident that may cause substantial harm to privacy, we will report to the Privacy Protection Authority without delay, and will notify the affected data subjects to the extent the incident may cause them substantial damage." },
  { t: "With respect to end-client data, we will notify the User (the data controller) within 72 hours of discovering the incident, by email to the address registered in the account. The notification will include the nature of the incident, the type of information exposed, the potential risks, and the recommended protective measures." },

  { h: "13. Minors" },
  { t: "The Service is intended for adult professionals. The Service must not be used if the User is under 18. We do not knowingly collect data of minors. If we become aware of such — the data will be deleted." },

  { h: "14. Changes to the Policy" },
  { t: "We may update this policy from time to time. In the event of material changes, the User will be asked to approve the updated policy upon their next login to the Application before being able to continue using the Service." },

  { h: "15. Privacy-Protection Management and Contact" },
  { t: "For any question, request, or inquiry regarding privacy:" },
  { t: "Email: simplicity.os.app@gmail.com" },
  { t: "For privacy-protection inquiries you may also contact our Data Protection Officer (DPO) at the email address above." },
  { t: "We will respond within a reasonable timeframe — up to 30 days, in accordance with the requirements of the law." },

  { t: `This policy is effective as of the date of its publication. Version ${PRIVACY_VERSION} — Beta.` },
]

export const TERMS_BLOCKS = [
  { h: "1. Acceptance of Terms" },
  { t: "Use of the Simplicity service (the \"Service\") constitutes full, informed, and irrevocable consent to the terms set out in this document. If you do not agree — please discontinue use." },
  { t: "The Service is operated by Benaya Dor, exempt dealer (עוסק פטור, an Israeli small-business tax status), Israel (\"we\", the \"Operator\")." },

  { h: "2. Definition of the Service" },
  { t: "Simplicity is a Practice OS (practice-management system) intended for coaches, mentors, and therapists. The Service enables the management of clients, sessions, finances, goals, and calendar sync." },
  { t: "The Service is provided \"as is\" (AS IS) during the beta period, with no commitment to full availability or to specific features." },

  { h: "3. Registration and Account" },
  { t: "You must be 18 or older to use the Service." },
  { t: "You are responsible for safeguarding your account access credentials and for all activity carried out under it." },
  { t: "Accurate and up-to-date information must be provided upon registration." },

  { h: "4. Permitted and Prohibited Use" },
  { t: "Permitted:" },
  { t: "Managing your professional practice — clients, sessions, finances." },
  { t: "Importing your existing data." },
  { t: "Exporting your data at any time." },
  { t: "Prohibited:" },
  { t: "Using the Service for unlawful purposes." },
  { t: "Uploading content that is offensive, misleading, or that infringes third-party rights." },
  { t: "Attempting to hack, disrupt, or access other users' data, or to circumvent security measures." },
  { t: "Using bots, crawlers/spiders, or automated tools for data mining or data extraction from the Service." },
  { t: "Using the Service's content or its data to train artificial-intelligence models (Machine Learning/LLM) without explicit written permission." },
  { t: "Commercial use of the Service beyond managing your personal practice — without a separate agreement." },
  { t: "Transferring the account to a third party." },

  { h: "5. Payment and Subscription" },
  { t: "During the beta period the Service is provided free of charge to invited users." },
  { t: "Upon the launch of a commercial version:" },
  { t: "Pricing will be published in advance in the Application." },
  { t: "At least 30 days' notice will be given before any charge takes effect." },
  { t: "Non-payment may result in suspension of access to the Service. Data will be retained for 60 days from the date of suspension." },
  { t: "Cancellations and refunds — any request to cancel a transaction will be handled in accordance with the provisions of the law, including the Consumer Protection Law, 5741-1981 and the regulations thereunder. There are no refunds for usage periods that have already been charged, except in cases of a material fault on the part of the Operator or as required by law." },
  { t: "Upon charging, a digital receipt and a duly issued electronic document will be issued to document the transaction, in accordance with Amendment 73 to the Consumer Protection Law." },

  { h: "6. Intellectual Property" },
  { t: "All of Simplicity's code, design, logo, and content are the property of the Operator." },
  { t: "The data you enter into the Service is entirely yours — we acquire no right in it." },
  { t: "You may not copy, reproduce, or distribute parts of the Service without written permission." },
  { t: "Feedback and improvement suggestions — any feedback, comment, idea, or improvement suggestion you provide to us in connection with the Service shall become the property of the Operator, who shall be entitled to make any use of it (including incorporating it into future versions) without consideration or credit." },

  { h: "7. Limitation of Liability and Indemnification" },
  { t: "The Service, the interfaces, and the integrations are provided \"as is\" (AS IS / AS AVAILABLE), with no commitment to continuous availability or to data integrity. The Operator makes reasonable efforts toward proper operation but does not warrant that the Service will be free from faults." },
  { t: "The User is aware of the risks inherent to a service of this kind:" },
  { t: "Planned and unplanned downtime; there is no guarantee of full availability." },
  { t: "Loss of data or impairment of its integrity as a result of technical faults; it is the User's responsibility to perform periodic backups." },
  { t: "Changes to API interfaces, features, or integrations, which may be made without prior notice." },
  { t: "Failures in third-party services on which the Service relies (infrastructure providers, Google, etc.)." },
  { t: "Despite reasonable security measures, there is no absolute guarantee against cyber intrusions or unauthorized access." },
  { t: "Liability cap — the Operator's total liability to the User for proven direct damages shall not exceed the amount paid by the User in the 12 months preceding the event, or ₪2,000, whichever is higher." },
  { t: "This limitation shall not apply to bodily injury or death arising from negligence, to a breach of the duty of privacy on the part of the Operator, to a willful act or gross negligence, or to other damages for which the law does not permit liability to be limited." },
  { t: "Indemnification — the User undertakes to indemnify the Operator for any damage or reasonable expense (including reasonable attorney's fees) incurred by it as a result of a fundamental breach of these terms by the User or as a result of unlawful use of the Service." },

  { h: "8. Suspension and Account Deletion" },
  { t: "The Operator may suspend or delete an account that breaches these terms, without prior notice in severe cases (such as a severe breach, fraud, a security compromise, or an immediate legal requirement)." },
  { t: "In ordinary cases — 7 days' notice will be given before suspension, with the option to appeal by email." },
  { t: "The User may delete their account at any time from the Application settings." },

  { h: "9. Changes to the Terms" },
  { t: "We will notify of material changes to the terms of use by means of a prominent notice in the Application and/or a notice to the User's email address, at least 30 days in advance. Continued use after the changes take effect constitutes consent." },
  { t: "A User who does not agree to a material change may discontinue use and request the closure of their account before the date on which the changes take effect." },

  { h: "10. Governing Law and Jurisdiction" },
  { t: "These terms are subject to the laws of the State of Israel. Exclusive jurisdiction — the competent courts of the Tel Aviv-Yafo District." },

  { h: "11. Dispute Resolution" },
  { t: "Initial contact — in any dispute or complaint, please contact us first at simplicity.os.app@gmail.com in an attempt to resolve the matter amicably." },
  { t: "Arbitration — if the dispute is not resolved within 30 days of the initial contact, the dispute shall be decided by a single arbitrator appointed by agreement of the parties. The arbitration proceedings shall be confidential, and this clause constitutes an arbitration agreement under the Arbitration Law, 5728-1968. Nothing in the foregoing shall prevent applying to a small-claims court, or requesting interim relief from the competent court." },
  { t: "Waiver of class action — the User agrees to resolve any dispute on an individual basis only, and waives their right to participate in a class action against the Operator, to the extent permitted by law." },

  { h: "12. Force Majeure" },
  { t: "The Operator shall not bear liability for non-performance or delay in performing its obligations arising from circumstances beyond its reasonable control, including war, acts of terror, a state of emergency, an epidemic, a natural disaster, a strike, faults in communications/electricity/internet infrastructure, or unforeseen regulatory orders and directives. In such a case, the performance dates shall be postponed in accordance with the period of the event." },

  { h: "13. Severability" },
  { t: "Should a competent tribunal determine that any provision of these terms is void or unenforceable, the validity of the remaining provisions shall not be impaired, and the void provision shall be replaced with a valid provision as close as possible to the original intent of the parties." },

  { h: "14. General and Assignment of Rights" },
  { t: "Failure to exercise, or delay in exercising, any of the Operator's rights shall not be deemed a waiver of that right (No Waiver)." },
  { t: "The Operator may assign its rights and obligations under these terms to a third party, subject to 30 days' prior notice to the User; the User may not assign their rights without the Operator's prior written consent." },

  { h: "15. Contact" },
  { t: "Email: simplicity.os.app@gmail.com" },
  { t: "We will respond within 14 business days." },

  { t: `These terms are effective as of the date of their publication. Version ${TERMS_VERSION} — Beta.` },
]

export const DPA_BLOCKS = [
  { h: "1. The Parties" },
  { t: "This agreement is entered into between:" },
  { t: "The data processor: Benaya Dor, exempt dealer (עוסק פטור, an Israeli small-business tax status), operator of the Simplicity service (the \"Processor\")." },
  { t: "The data controller: the User registered with the Service — a coach, mentor, or therapist (the \"Client\")." },
  { t: "This agreement governs the terms of processing the Client's end-client data by the Processor, in accordance with the Protection of Privacy Law, 5741-1981 and its regulations (including Amendment 13 and the Privacy Protection (Information Security) Regulations, 5777-2017), and in accordance with the GDPR where relevant." },

  { h: "2. Definitions" },
  { t: "End-client data — any personal information entered into the Service by the Client about the persons they support, including names, contact details, session notes, and summaries." },
  { t: "Processing — any operation performed on the data: collection, storage, modification, viewing, deletion." },
  { t: "Security breach — unauthorized access to, loss of, exposure of, or modification of personal data." },
  { t: "Sub-processor (subcontractor) — a third party that processes end-client data on behalf of the Processor for the purpose of providing the Service (see Section 4.2)." },

  { h: "3. Purpose of Processing" },
  { t: "The Processor processes end-client data solely for the following purposes:" },
  { t: "Providing the practice-management service to the Client (managing clients, sessions, finances, goals)." },
  { t: "Technical operation, backups, and securing the system." },
  { t: "Technical support for the Client's inquiries." },
  { t: "The Processor will not process end-client data for any other purpose, including advertising or research, without explicit consent. In any case, the Processor does not use end-client data to train artificial-intelligence models of any kind." },

  { h: "4. Processor's Obligations" },
  { h2: "4.1 Information security" },
  { t: "Storage of data on Supabase servers in Ireland (EU), encrypted at rest (at-rest) at the infrastructure level and in transit (HTTPS/TLS)." },
  { t: "Encryption of all communication using the HTTPS/TLS protocol." },
  { t: "Restriction of internal access to data on a need-to-know basis." },
  { t: "Isolation of data separately for each User (Row-Level Security) — each User accesses only their own data; the team's access to the infrastructure is restricted to authorized personnel for operational, support, and backup purposes." },
  { t: "The security measures are implemented in accordance with the Privacy Protection (Information Security) Regulations, 5777-2017, at a medium security level (Level 3): password and permission procedures, logging and monitoring of access (Logs), and periodic audits. A Data Protection Officer (DPO) has been appointed." },
  { h2: "4.2 Subcontractors" },
  { t: "The Processor uses the following subcontractors for the purpose of providing the Service:" },
  { t: "Supabase (Ireland) — data storage." },
  { t: "Vercel (USA) — hosting of the user interface." },
  { t: "Google (USA) — authentication and calendar." },
  { t: "Resend (USA) — email." },
  { t: "All subcontractors are subject to appropriate data processing agreements (DPAs), which bind them to a level of protection similar to that of this agreement. The Processor will notify the Client of any material addition or replacement of a subcontractor, and will not transfer end-client data to a sub-processor that is not subject to these obligations." },
  { h2: "4.3 Security breach" },
  { t: "In the event of a security breach affecting end-client data, the Processor will notify the Client within 72 hours of discovery, by email to the address registered in the account. The notification will include the nature of the incident, the type of information exposed, and the measures taken." },
  { t: "In a severe security incident, the Processor will also report to the Privacy Protection Authority as required by law, and will assist the Client in fulfilling the reporting obligations applicable to it as the data controller." },
  { h2: "4.4 Data deletion" },
  { t: "Upon deletion of the Client's account, all end-client data will be permanently deleted within 30 days. No copy whatsoever will remain except for technical backups, which will likewise be deleted within an additional 90 days." },
  { h2: "4.5 Assistance to the data controller" },
  { t: "The Processor will assist the Client, to a reasonable extent, in responding to requests from end clients to exercise their rights (access, correction, deletion, portability), and in complying with the Client's obligations under the law." },
  { h2: "4.6 International transfer" },
  { t: "To the extent that processing the data involves a transfer outside Israel (such as subcontractors in the USA), the transfer will be carried out subject to an appropriate legal mechanism — an Adequacy Decision, Standard Contractual Clauses (SCC), or an equivalent contractual undertaking." },
  { h2: "4.7 Confidentiality" },
  { t: "The Processor ensures that the authorized personnel on its behalf who access end-client data are bound to maintain confidentiality." },

  { h: "5. Client's Obligations" },
  { t: "The Client declares that it has a lawful basis for collecting and processing its end-client data." },
  { t: "The Client is responsible for obtaining the required consents from its end clients to store information about them." },
  { t: "The Client is responsible for the accuracy of the information it enters into the system." },
  { t: "The Client will not enter into the system particularly sensitive data (such as identity numbers, diagnosed medical data) beyond what is necessary for managing the practice." },

  { h: "6. Client's Rights" },
  { t: "To request a list of all end-client data stored on its behalf." },
  { t: "To export all the data at any time in a structured format." },
  { t: "To demand the deletion of specific data." },
  { t: "To receive notification within 72 hours of any security breach." },
  { t: "To exercise these rights: simplicity.os.app@gmail.com" },

  { h: "7. Term and Termination" },
  { t: "This agreement is in effect as long as the Client uses the Service. Upon termination of use — whether at the Client's initiative or at the Processor's initiative — the provisions of Section 4.4 (Data deletion) shall apply." },

  { h: "8. Governing Law" },
  { t: "This agreement is subject to the laws of the State of Israel. Exclusive jurisdiction — the competent courts in Israel." },

  { t: `This agreement enters into effect upon the User's approval at the time of registration for the Service. Version ${DPA_VERSION} — June 2026.` },
]
