/* Spanish legal content — AI translation of the Hebrew source, PENDING HUMAN LEGAL REVIEW. Faithful translation; Israeli law governs. Structure mirrors legalContent.js. */
import { PRIVACY_VERSION, DPA_VERSION, TERMS_VERSION } from '../../lib/legal'

export const PRIVACY_META = `Simplicity · Versión ${PRIVACY_VERSION} · Beta · Actualizado: junio de 2026`
export const TERMS_META = `Simplicity · Versión ${TERMS_VERSION} · Beta · Actualizado: junio de 2026`
export const DPA_META = `Acuerdo de Procesamiento de Datos · Versión ${DPA_VERSION} · junio de 2026`

export const PRIVACY_BLOCKS = [
  { h: "1. Introducción" },
  { t: "Simplicity (“el Servicio”, “la Aplicación”) es un Practice OS (sistema de gestión de práctica) destinado a coaches, mentores y terapeutas. El Servicio es operado por Benaya Dor (“nosotros”, “el Operador”)." },
  { t: "Esta política de privacidad explica qué datos se recopilan, cómo se procesan y almacenan, cuáles son tus derechos y cómo puedes contactarnos. La política se ha redactado de conformidad con la Ley de Protección de la Privacidad de Israel, 5741-1981 y sus reglamentos (incluida la Enmienda 13), y con el RGPD en la medida en que resulte relevante." },
  { t: "El uso del Servicio constituye la aceptación de los términos detallados en esta política. Si no estás de acuerdo, por favor cesa el uso." },

  { h: "2. Definiciones principales" },
  { t: "Usuario: coach, mentor o terapeuta que se registra en el Servicio y lo utiliza para gestionar su práctica." },
  { t: "Cliente final: la persona a quien el Usuario acompaña, y cuyos datos son introducidos en la Aplicación por el Usuario. El cliente final no es parte directa del acuerdo con Simplicity." },
  { t: "Datos del Usuario: toda información creada, introducida o sincronizada en el Servicio por el Usuario." },
  { t: "Operador: Benaya Dor, comerciante exento (עוסק פטור, un régimen fiscal israelí para pequeñas empresas), Israel. Correo electrónico: simplicity.os.app@gmail.com" },

  { h: "3. Relación entre las partes — Controller y Processor" },
  { t: "Respecto de los datos de los clientes finales: el Usuario es el responsable del tratamiento (Controller), es decir, quien decide qué recopilar y para qué. Simplicity es el encargado del tratamiento (Processor): procesa los datos únicamente conforme a las instrucciones del Usuario y con el fin de prestar el Servicio." },
  { t: "Respecto de los datos del propio Usuario (cuenta, perfil, datos de uso): Simplicity es el responsable del tratamiento (Controller)." },
  { t: "La responsabilidad de obtener los consentimientos informados de los clientes finales, así como de la licitud de la recopilación de información sobre ellos y de su fiabilidad, recae en su totalidad únicamente sobre el Usuario empresarial. El Operador no asumirá responsabilidad alguna frente a terceros cuyos datos hayan sido introducidos en el sistema por el Usuario." },

  { h: "4. Datos que se recopilan" },
  { h2: "4.1 Datos del Usuario" },
  { t: "Nombre completo, dirección de correo electrónico, contraseña cifrada (o autenticación de Google), al momento del registro." },
  { t: "Profesión/cargo, para la personalización de la interfaz." },
  { t: "Datos de uso: actividad general con el fin de operar y mejorar el Servicio." },
  { h2: "4.2 Datos de los clientes finales (introducidos por el Usuario)" },
  { t: "El Usuario introduce manualmente datos sobre sus clientes finales. Estos datos pueden incluir:" },
  { t: "Nombre completo, teléfono, dirección de correo electrónico." },
  { t: "Notas, resúmenes de sesiones y reflexiones; estos pueden contener información sensible." },
  { t: "Datos financieros: costo por sesión, historial de pagos." },
  { t: "Estos datos se almacenan en servidores de la Unión Europea, aislados de forma separada para cada usuario (Row-Level Security: cada usuario accede únicamente a sus propios datos), y protegidos mediante cifrado de almacenamiento a nivel de la infraestructura (at-rest) y cifrado de transmisión (HTTPS/TLS). Existe un acceso técnico limitado a la infraestructura únicamente con fines de operación, soporte y respaldo." },
  { h2: "4.3 Sincronización con Google Calendar (opcional)" },
  { t: "Si el Usuario decide conectar su calendario de Google, la Aplicación solicita acceso solo de lectura (calendar.readonly) al calendario principal. Se guardan: el título del evento, la hora de inicio y de fin, y la duración. No se guardan: la descripción, la lista de participantes ni la ubicación." },
  { t: "Los tokens de acceso al calendario se almacenan de forma segura y se limitan únicamente al acceso del sistema. El calendario puede desconectarse en cualquier momento; la desconexión cancela el permiso de acceso en Google." },
  { h2: "4.4 Información técnica e identificadores digitales (Enmienda 13)" },
  { t: "De conformidad con la Enmienda 13 de la Ley de Protección de la Privacidad, la información técnica tal como la dirección IP, los datos de ubicación y los identificadores digitales se considera información personal a todos los efectos, y la tratamos con el nivel de seguridad y privacidad requerido. Información de este tipo se recopila de forma limitada únicamente con fines de operación y seguridad del Servicio." },
  { h2: "4.5 Carácter voluntario de la entrega de la información" },
  { t: "No tienes ninguna obligación legal de entregar la información; su entrega se realiza por tu voluntad y con tu consentimiento, para los fines detallados en la sección 5. No obstante, sin la información imprescindible (como el nombre y el correo electrónico al momento del registro) no podremos prestar el Servicio." },

  { h: "5. Cómo se utilizan los datos" },
  { t: "Prestación del Servicio: gestión de clientes, sesiones, finanzas y objetivos para el Usuario." },
  { t: "Mejora del Servicio: análisis de patrones de uso anónimos con fines de desarrollo." },
  { t: "Soporte técnico: atención de consultas e incidencias." },
  { t: "Seguridad: detección de uso indebido y prevención de accesos no autorizados." },
  { t: "Simplicity no vende datos ni los comparte con entidades publicitarias. No utilizamos información personal para el entrenamiento de modelos de inteligencia artificial, y no utilizamos el contenido de las notas, los resúmenes ni los datos de los clientes finales para entrenar modelos de ningún tipo." },

  { h: "6. Almacenamiento y seguridad de la información" },
  { h2: "6.1 Ubicación del almacenamiento" },
  { t: "Los datos del Servicio se almacenan en servidores de Supabase en Irlanda (región eu-west-1), en el ámbito de la Unión Europea, de conformidad con el RGPD." },
  { h2: "6.2 Cifrado" },
  { t: "Los datos están cifrados en el almacenamiento (at-rest) a nivel de la infraestructura del proveedor de alojamiento (Supabase), y aislados para cada usuario mediante Row-Level Security, de modo que cada usuario accede únicamente a sus propios datos." },
  { t: "Toda la comunicación entre la Aplicación y el servidor está cifrada mediante el protocolo HTTPS/TLS." },
  { t: "Las contraseñas de los usuarios se guardan únicamente en forma de hash (no en texto visible)." },
  { h2: "6.3 Acceso interno" },
  { t: "El equipo de Simplicity tiene un acceso técnico limitado a la infraestructura de datos con fines de operación, soporte y respaldo, restringido únicamente a personas autorizadas. No vendemos datos, no los compartimos con anunciantes y no utilizamos el contenido de las notas para entrenar modelos (véase la sección 5)." },
  { h2: "6.4 Nivel de seguridad y gestión de la protección de la privacidad" },
  { t: "El Servicio implementa medidas de seguridad de conformidad con el Reglamento de Protección de la Privacidad (Seguridad de la Información), 5777-2017, en un nivel de seguridad medio (nivel 3): procedimientos de contraseñas complejas y gestión de permisos, registro y seguimiento de los accesos a la base de datos (Logs), y auditorías de seguridad periódicas." },
  { t: "Se ha designado un Delegado de Protección de Datos (DPO) responsable de los asuntos de protección de la privacidad en la organización; se puede contactar con él en la dirección simplicity.os.app@gmail.com." },
  { h2: "6.5 Proveedores de servicios de terceros" },
  { t: "Simplicity utiliza los siguientes proveedores de servicios para el funcionamiento del Servicio:" },
  { t: "Supabase (Irlanda): base de datos y autenticación de usuarios." },
  { t: "Vercel (EE. UU.): alojamiento de la interfaz de usuario. Puede procesar datos de IP y registros (logs)." },
  { t: "Google (EE. UU.): autenticación OAuth y sincronización de calendario, sujeto a la política de privacidad de Google." },
  { t: "Resend (EE. UU.): envío de mensajes de correo electrónico desde el sistema." },
  { t: "Analítica: futuro; se añadirá con la activación de un servicio de analítica. Actualmente no utilizamos herramientas de analítica de terceros." },
  { t: "Estos proveedores están sujetos a acuerdos de procesamiento de datos (DPA) adecuados. La información que se les transfiere se transfiere, en la medida de lo posible, de forma anónima o codificada." },

  { h: "7. Transferencia internacional de información" },
  { t: "Algunos de nuestros proveedores de servicios están ubicados fuera de Israel (como Vercel y Google en EE. UU.). La transferencia de información hacia y desde los países de la Unión Europea se realiza de conformidad con la Decisión de Adecuación (Adequacy Decision) otorgada a Israel." },
  { t: "En las transferencias a países que no cuentan con un nivel de protección adecuado, garantizamos que la transferencia se realiza mediante un mecanismo legal apropiado: Cláusulas Contractuales Tipo (SCC), consentimiento expreso del sujeto de los datos, o un compromiso contractual del receptor de cumplir con los estándares de la protección de la privacidad israelí." },

  { h: "8. Conservación de datos y eliminación" },
  { h2: "8.1 Mientras la cuenta esté activa" },
  { t: "Los datos se conservan mientras la cuenta esté activa, con el fin de prestar el Servicio." },
  { h2: "8.2 Eliminación de la cuenta" },
  { t: "El Usuario puede eliminar su cuenta en cualquier momento desde la configuración de la Aplicación. Tras la solicitud de eliminación:" },
  { t: "La solicitud puede cancelarse dentro de los 30 días." },
  { t: "Transcurridos 30 días, todos los datos se eliminan de forma permanente, incluidos los datos de los clientes finales, las sesiones, las notas y los archivos." },
  { t: "No es posible recuperar los datos tras la eliminación definitiva." },
  { h2: "8.3 Exportación de datos" },
  { t: "El Usuario puede exportar todos sus datos en cualquier momento desde la configuración de la Aplicación, en formato Excel. La exportación incluye: clientes, sesiones, notas, transacciones, objetivos y respuestas diarias, según la elección del Usuario." },

  { h: "9. Derechos del Usuario" },
  { t: "De conformidad con la Ley de Protección de la Privacidad de Israel (1981) y con el RGPD, el Usuario tiene los siguientes derechos:" },
  { t: "Acceso (artículo 13 de la Ley): solicitar ver qué datos se conservan acerca de él." },
  { t: "Rectificación (artículo 14 de la Ley): exigir la corrección de información errónea, incompleta o desactualizada." },
  { t: "Eliminación / derecho al olvido: exigir la eliminación de los datos (véase la sección 8.2), sujeto a las excepciones previstas por la ley." },
  { t: "Portabilidad: exportar los datos en un formato estructurado y legible por máquina (véase la sección 8.3)." },
  { t: "Oposición: oponerse al procesamiento de datos con fines de marketing directo o en ciertos otros casos." },
  { t: "Prevención de correo no deseado (artículo 30A de la Ley de Comunicaciones): la mensajería publicitaria solo se enviará previo consentimiento expreso; puedes darte de baja de la lista de distribución en cualquier momento, sin costo, mediante el enlace de baja al pie de cada mensaje o contactando a simplicity.os.app@gmail.com." },
  { t: "Para ejercer estos derechos: simplicity.os.app@gmail.com; responderemos dentro de los 30 días. Para proteger la información, verificaremos la identidad del solicitante antes de entregar, corregir o eliminar datos." },

  { h: "10. Uso de datos con fines de marketing" },
  { t: "Sujeto a un consentimiento expreso al momento del registro, podremos utilizar la dirección de correo electrónico del Usuario para crear audiencias publicitarias personalizadas (como Lookalike Audiences) en plataformas como Meta, con el fin de ampliar la base de usuarios de Simplicity." },
  { t: "Este uso: está condicionado únicamente a un consentimiento expreso, no marcado por defecto en el registro. Se limita únicamente al correo electrónico del Usuario, no a datos de clientes finales, ni notas, ni contenido. Es cancelable en cualquier momento, contactando a simplicity.os.app@gmail.com." },
  { t: "Un usuario que no haya dado su consentimiento no será incluido en ninguna acción de marketing de este tipo." },

  { h: "11. Cookies y rastreo" },
  { t: "La Aplicación utiliza cookies técnicas necesarias para su funcionamiento (mantener el estado de la sesión). Estas cookies están exentas de consentimiento." },
  { t: "Sujeto a tu consentimiento — otorgado a través del banner de cookies del sitio — también podemos utilizar cookies de analítica y publicidad, incluidas cookies para medir el uso, mostrar anuncios relevantes y realizar retargeting a los visitantes de la página de aterrizaje. Estas cookies no esenciales no se cargan hasta que des tu consentimiento, y puedes rechazarlas o retirar tu consentimiento en cualquier momento a través del banner." },
  { t: "Las fuentes tipográficas de la Aplicación se cargan desde Google Fonts; esta operación expone la dirección IP del Usuario a los servidores de Google. No se recopila información adicional." },

  { h: "12. Notificación de incidente de seguridad" },
  { t: "De conformidad con el Reglamento de Protección de la Privacidad (Seguridad de la Información), 5777-2017, en caso de un incidente de seguridad grave que pueda causar un daño real a la privacidad, lo informaremos a la Autoridad de Protección de la Privacidad sin demora, y notificaremos a los sujetos de los datos afectados en la medida en que el incidente pueda causarles un daño real." },
  { t: "Respecto de los datos de los clientes finales, notificaremos al Usuario (el responsable del tratamiento) dentro de las 72 horas desde el momento del descubrimiento del incidente, por correo electrónico a la dirección registrada en la cuenta. La notificación incluirá la naturaleza del incidente, el tipo de información expuesta, los riesgos potenciales y las medidas de protección recomendadas." },

  { h: "13. Menores" },
  { t: "El Servicio está destinado a profesionales adultos. No se debe utilizar el Servicio si la edad del Usuario es inferior a 18 años. No recopilamos a sabiendas datos de menores. Si llegamos a tener conocimiento de ello, los datos serán eliminados." },

  { h: "14. Cambios en la política" },
  { t: "Podremos actualizar esta política de vez en cuando. En caso de cambios sustanciales, se solicitará al Usuario que apruebe la política actualizada en su siguiente ingreso a la Aplicación antes de poder seguir utilizando el Servicio." },

  { h: "15. Gestión de la protección de la privacidad y contacto" },
  { t: "Para cualquier pregunta, solicitud o consulta en materia de privacidad:" },
  { t: "Correo electrónico: simplicity.os.app@gmail.com" },
  { t: "Para consultas en materia de protección de la privacidad también puedes contactar a nuestro Delegado de Protección de Datos (DPO) en la dirección de correo electrónico indicada arriba." },
  { t: "Responderemos dentro de un plazo razonable, de hasta 30 días, conforme a los requisitos de la ley." },

  { t: `Esta política entra en vigor a partir de la fecha de su publicación. Versión ${PRIVACY_VERSION} — Beta.` },
]

export const TERMS_BLOCKS = [
  { h: "1. Aceptación de los términos" },
  { t: "El uso del servicio Simplicity (“el Servicio”) constituye una aceptación plena, informada e irrevocable de los términos detallados en este documento. Si no estás de acuerdo, por favor cesa el uso." },
  { t: "El Servicio es operado por Benaya Dor, comerciante exento (עוסק פטור, un régimen fiscal israelí para pequeñas empresas), Israel (“nosotros”, “el Operador”)." },

  { h: "2. Definición del Servicio" },
  { t: "Simplicity es un Practice OS (sistema de gestión de práctica) destinado a coaches, mentores y terapeutas. El Servicio permite la gestión de clientes, sesiones, finanzas, objetivos y sincronización de calendario." },
  { t: "El Servicio se proporciona “tal cual” (AS IS) durante el período beta, sin compromiso de disponibilidad total ni de funcionalidades específicas." },

  { h: "3. Registro y cuenta" },
  { t: "Debes tener 18 años o más para utilizar el Servicio." },
  { t: "Eres responsable de proteger los datos de acceso a tu cuenta y de toda actividad que se realice bajo ella." },
  { t: "Se debe proporcionar información precisa y actualizada al momento del registro." },

  { h: "4. Uso permitido y prohibido" },
  { t: "Permitido:" },
  { t: "Gestionar tu práctica profesional: clientes, sesiones, finanzas." },
  { t: "Importar tus datos existentes." },
  { t: "Exportar tus datos en cualquier momento." },
  { t: "Prohibido:" },
  { t: "Utilizar el Servicio para fines ilícitos." },
  { t: "Subir contenido ofensivo, engañoso o que vulnere derechos de terceros." },
  { t: "Intentar vulnerar, perturbar o acceder a datos de otros usuarios, o eludir las medidas de seguridad." },
  { t: "Utilizar bots, rastreadores (Crawlers/Spiders) o herramientas automatizadas para la minería de datos (Data Mining) o la extracción de datos del Servicio." },
  { t: "Utilizar los contenidos del Servicio o sus datos para el entrenamiento de modelos de inteligencia artificial (Machine Learning/LLM) sin autorización expresa por escrito." },
  { t: "Uso comercial del Servicio más allá de la gestión de tu propia práctica personal, sin un acuerdo separado." },
  { t: "Transferir la cuenta a un tercero." },

  { h: "5. Pago y suscripción" },
  { t: "Durante el período beta, el Servicio se proporciona sin costo a los usuarios invitados." },
  { t: "Con el lanzamiento de una versión comercial:" },
  { t: "La tarificación se publicará por anticipado en la Aplicación." },
  { t: "Se dará un aviso de al menos 30 días antes de la entrada en vigor de los cargos." },
  { t: "El impago podrá conllevar la suspensión del acceso al Servicio. Los datos se conservarán durante 60 días desde la fecha de la suspensión." },
  { t: "Cancelaciones y reembolsos: toda solicitud de cancelación de una transacción se tramitará de conformidad con las disposiciones de la ley, incluida la Ley de Protección del Consumidor, 5741-1981 y sus reglamentos. No hay reembolsos por períodos de uso ya facturados, salvo en casos de una falla sustancial por parte del Operador o según lo exija la ley." },
  { t: "Al momento de la facturación se emitirá un recibo digital y un documento electrónico conforme a la ley para documentar la transacción, de conformidad con la Enmienda 73 de la Ley de Protección del Consumidor." },

  { h: "6. Propiedad intelectual" },
  { t: "Todo el código, el diseño, el logotipo y el contenido de Simplicity son propiedad del Operador." },
  { t: "Los datos que introduces en el Servicio son enteramente tuyos; no adquirimos ningún derecho sobre ellos." },
  { t: "No estás autorizado a copiar, reproducir ni distribuir partes del Servicio sin autorización por escrito." },
  { t: "Comentarios y sugerencias de mejora: todo comentario, respuesta, idea o sugerencia de mejora que nos transmitas en relación con el Servicio pasará a ser propiedad del Operador, quien podrá hacer de ellos cualquier uso (incluida su incorporación en versiones futuras) sin contraprestación ni atribución." },

  { h: "7. Limitación de responsabilidad e indemnización" },
  { t: "El Servicio, las interfaces y las integraciones se proporcionan “tal cual” (AS IS / AS AVAILABLE), sin compromiso de disponibilidad continua ni de integridad de los datos. El Operador realiza esfuerzos razonables para un funcionamiento correcto, pero no garantiza que el Servicio esté libre de fallas." },
  { t: "El Usuario es consciente de los riesgos propios de un servicio de este tipo:" },
  { t: "Interrupciones (Downtime) planificadas y no planificadas; no hay garantía de disponibilidad total." },
  { t: "Pérdida de datos o menoscabo de su integridad como consecuencia de fallas técnicas; es responsabilidad del Usuario realizar copias de seguridad periódicas." },
  { t: "Cambios en las interfaces de API, en las funcionalidades o en las integraciones, que pueden realizarse sin aviso previo." },
  { t: "Fallas en servicios de terceros sobre los que se basa el Servicio (proveedores de infraestructura, Google, etc.)." },
  { t: "A pesar de medidas de seguridad razonables, no hay garantía absoluta frente a intrusiones cibernéticas o accesos no autorizados." },
  { t: "Límite de responsabilidad: la responsabilidad total del Operador frente al Usuario por daños directos probados no excederá el importe pagado por el Usuario en los 12 meses anteriores al incidente, o ₪2,000, el que sea mayor de ambos." },
  { t: "Esta limitación no se aplicará a los daños corporales o la muerte derivados de negligencia, a la vulneración del deber de privacidad por parte del Operador, a un acto doloso o negligencia grave, ni a otros daños cuya responsabilidad la ley no permite limitar." },
  { t: "Indemnización: el Usuario se compromete a indemnizar al Operador por todo daño o gasto razonable (incluidos honorarios razonables de abogado) que se le ocasionen como consecuencia de un incumplimiento esencial de estos términos por parte del Usuario o de un uso ilícito del Servicio." },

  { h: "8. Suspensión y eliminación de la cuenta" },
  { t: "El Operador podrá suspender o eliminar una cuenta que incumpla estos términos, sin aviso previo en casos graves (como un incumplimiento grave, falsificación, vulneración de la seguridad o una exigencia legal inmediata)." },
  { t: "En casos ordinarios se dará un aviso de 7 días antes de la suspensión, con la posibilidad de apelar por correo electrónico." },
  { t: "El Usuario puede eliminar su cuenta en cualquier momento desde la configuración de la Aplicación." },

  { h: "9. Cambios en los términos" },
  { t: "Notificaremos los cambios sustanciales en los términos de uso mediante un aviso destacado en la Aplicación y/o un aviso a la dirección de correo electrónico del Usuario, al menos 30 días por anticipado. La continuación del uso tras la entrada en vigor de los cambios constituye una aceptación." },
  { t: "Un usuario que no esté de acuerdo con un cambio sustancial podrá cesar el uso y solicitar el cierre de su cuenta antes de la fecha de entrada en vigor de los cambios." },

  { h: "10. Ley aplicable y jurisdicción" },
  { t: "Estos términos están sujetos a las leyes del Estado de Israel. La jurisdicción exclusiva corresponde a los tribunales competentes del Distrito de Tel Aviv-Yafo." },

  { h: "11. Resolución de controversias" },
  { t: "Contacto inicial: ante cualquier controversia o reclamo, por favor contáctanos primero en la dirección simplicity.os.app@gmail.com para intentar resolver el asunto de manera amistosa." },
  { t: "Arbitraje: si la controversia no se resuelve dentro de los 30 días desde el contacto inicial, la controversia será dirimida por un árbitro único designado de común acuerdo por las partes. El procedimiento de arbitraje será confidencial, y esta cláusula constituye un acuerdo de arbitraje conforme a la Ley de Arbitraje, 5728-1968. Nada de lo anterior impide acudir a un tribunal de causas menores, ni solicitar medidas cautelares al tribunal competente." },
  { t: "Renuncia a la acción colectiva: el Usuario acepta resolver toda controversia únicamente de forma individual, y renuncia a su derecho a participar en una acción colectiva contra el Operador, en la medida en que ello esté permitido por la ley." },

  { h: "12. Fuerza mayor" },
  { t: "El Operador no asumirá responsabilidad por el incumplimiento o el retraso en el cumplimiento de sus obligaciones derivado de circunstancias fuera de su control razonable, incluidas guerra, actos de terrorismo, estado de emergencia, pandemia, desastre natural, huelga, fallas en las infraestructuras de comunicaciones/electricidad/internet, u órdenes y disposiciones regulatorias imprevisibles. En tal caso, los plazos de ejecución se aplazarán conforme al período del evento." },

  { h: "13. Divisibilidad de las cláusulas" },
  { t: "Si una instancia competente determina que alguna disposición de estos términos es nula o no ejecutable, no se verá afectada la validez del resto de las disposiciones, y la disposición nula será reemplazada por una disposición válida lo más cercana posible a la intención original de las partes." },

  { h: "14. Disposiciones generales y cesión de derechos" },
  { t: "La falta de ejercicio o la demora en el ejercicio de cualquier derecho del Operador no se considerará una renuncia a dicho derecho (No Waiver)." },
  { t: "El Operador podrá ceder sus derechos y obligaciones conforme a estos términos a un tercero, previo aviso de 30 días al Usuario; el Usuario no podrá ceder sus derechos sin el consentimiento previo y por escrito del Operador." },

  { h: "15. Contacto" },
  { t: "Correo electrónico: simplicity.os.app@gmail.com" },
  { t: "Responderemos dentro de 14 días hábiles." },

  { t: `Estos términos entran en vigor a partir de la fecha de su publicación. Versión ${TERMS_VERSION} — Beta.` },
]

export const DPA_BLOCKS = [
  { h: "1. Las partes" },
  { t: "Este acuerdo se celebra entre:" },
  { t: "El encargado del tratamiento (Processor): Benaya Dor, comerciante exento (עוסק פטור, un régimen fiscal israelí para pequeñas empresas), operador del servicio Simplicity (“el Encargado”)." },
  { t: "El responsable del tratamiento (Controller): el Usuario registrado en el Servicio, coach, mentor o terapeuta (“el Cliente”)." },
  { t: "Este acuerdo regula las condiciones del procesamiento de los datos de los clientes finales del Cliente por parte del Encargado, de conformidad con la Ley de Protección de la Privacidad de Israel, 5741-1981 y sus reglamentos (incluida la Enmienda 13 y el Reglamento de Protección de la Privacidad (Seguridad de la Información), 5777-2017), y de conformidad con el RGPD en la medida en que resulte relevante." },

  { h: "2. Definiciones" },
  { t: "Datos de los clientes finales: toda información personal introducida en el Servicio por el Cliente acerca de las personas a quienes acompaña, incluidos nombres, datos de contacto, notas de sesiones y resúmenes." },
  { t: "Procesamiento: toda operación que se realiza sobre los datos: recopilación, almacenamiento, modificación, consulta, eliminación." },
  { t: "Brecha de seguridad: acceso no autorizado, pérdida, exposición o modificación de datos personales." },
  { t: "Subencargado (proveedor secundario): un tercero que procesa datos de los clientes finales por cuenta del Encargado para la prestación del Servicio (véase la sección 4.2)." },

  { h: "3. Finalidad del procesamiento" },
  { t: "El Encargado procesa los datos de los clientes finales únicamente para las siguientes finalidades:" },
  { t: "Prestación del servicio de gestión de la práctica al Cliente (gestión de clientes, sesiones, finanzas, objetivos)." },
  { t: "Operación técnica, copias de seguridad y seguridad del sistema." },
  { t: "Soporte técnico para las consultas del Cliente." },
  { t: "El Encargado no procesará los datos de los clientes finales para ninguna otra finalidad, incluida publicidad o investigación, sin consentimiento expreso. En todo caso, el Encargado no utiliza los datos de los clientes finales para el entrenamiento de modelos de inteligencia artificial de ningún tipo." },

  { h: "4. Obligaciones del Encargado" },
  { h2: "4.1 Seguridad de la información" },
  { t: "Almacenamiento de los datos en servidores de Supabase en Irlanda (UE), cifrados en el almacenamiento (at-rest) a nivel de la infraestructura y en la transmisión (HTTPS/TLS)." },
  { t: "Cifrado de toda la comunicación mediante el protocolo HTTPS/TLS." },
  { t: "Restricción del acceso interno a los datos sobre la base del principio de necesidad de conocer (need-to-know)." },
  { t: "Aislamiento de los datos de cada usuario por separado (Row-Level Security): cada usuario accede únicamente a sus propios datos; el acceso del equipo a la infraestructura está restringido a personas autorizadas con fines de operación, soporte y respaldo." },
  { t: "Las medidas de seguridad se implementan de conformidad con el Reglamento de Protección de la Privacidad (Seguridad de la Información), 5777-2017, en un nivel de seguridad medio (nivel 3): procedimientos de contraseñas y permisos, registro y seguimiento de los accesos (Logs) y auditorías periódicas. Se ha designado un Delegado de Protección de Datos (DPO)." },
  { h2: "4.2 Proveedores secundarios" },
  { t: "El Encargado utiliza los siguientes proveedores secundarios para la prestación del Servicio:" },
  { t: "Supabase (Irlanda): almacenamiento de datos." },
  { t: "Vercel (EE. UU.): alojamiento de la interfaz de usuario." },
  { t: "Google (EE. UU.): autenticación y calendario." },
  { t: "Resend (EE. UU.): correo electrónico." },
  { t: "Todos los proveedores secundarios están sujetos a acuerdos de procesamiento de datos (DPA) adecuados, que los obligan a un nivel de protección similar al de este acuerdo. El Encargado notificará al Cliente la incorporación o el reemplazo sustancial de un proveedor secundario, y no transferirá datos de los clientes finales a un subencargado que no esté sujeto a estas obligaciones." },
  { h2: "4.3 Brecha de seguridad" },
  { t: "En caso de una brecha de seguridad que afecte a los datos de los clientes finales, el Encargado notificará al Cliente dentro de las 72 horas desde el momento del descubrimiento, por correo electrónico a la dirección registrada en la cuenta. La notificación incluirá la naturaleza del incidente, el tipo de información expuesta y las medidas adoptadas." },
  { t: "Ante un incidente de seguridad grave, el Encargado también informará a la Autoridad de Protección de la Privacidad según lo exija la ley, y asistirá al Cliente en el cumplimiento de las obligaciones de notificación que le incumben como responsable del tratamiento." },
  { h2: "4.4 Eliminación de datos" },
  { t: "Tras la eliminación de la cuenta del Cliente, todos los datos de los clientes finales se eliminarán de forma permanente dentro de los 30 días. No quedará ninguna copia salvo las copias de seguridad técnicas, que también se eliminarán dentro de 90 días adicionales." },
  { h2: "4.5 Asistencia al responsable del tratamiento" },
  { t: "El Encargado asistirá al Cliente, en una medida razonable, para responder a las solicitudes de los clientes finales relativas al ejercicio de sus derechos (acceso, rectificación, eliminación, portabilidad), y para el cumplimiento de las obligaciones del Cliente conforme a la ley." },
  { h2: "4.6 Transferencia internacional" },
  { t: "En la medida en que el procesamiento de los datos implique una transferencia fuera de Israel (como proveedores secundarios en EE. UU.), la transferencia se realizará sujeta a un mecanismo legal apropiado: Decisión de Adecuación, Cláusulas Contractuales Tipo (SCC) o un compromiso contractual equivalente." },
  { h2: "4.7 Confidencialidad" },
  { t: "El Encargado garantiza que las personas autorizadas por su cuenta que acceden a los datos de los clientes finales están obligadas a guardar confidencialidad." },

  { h: "5. Obligaciones del Cliente" },
  { t: "El Cliente declara que tiene una base legal para la recopilación y el procesamiento de los datos de sus clientes finales." },
  { t: "El Cliente es responsable de obtener los consentimientos necesarios de sus clientes finales para almacenar información sobre ellos." },
  { t: "El Cliente es responsable de la exactitud de la información que introduce en el sistema." },
  { t: "El Cliente no introducirá en el sistema datos especialmente sensibles (como números de identidad, datos médicos diagnosticados) más allá de lo necesario para la gestión de la práctica." },

  { h: "6. Derechos del Cliente" },
  { t: "Solicitar una lista de todos los datos de los clientes finales almacenados en su nombre." },
  { t: "Exportar todos los datos en cualquier momento en un formato estructurado." },
  { t: "Exigir la eliminación de datos específicos." },
  { t: "Recibir una notificación dentro de las 72 horas sobre cualquier brecha de seguridad." },
  { t: "Para ejercer estos derechos: simplicity.os.app@gmail.com" },

  { h: "7. Vigencia y terminación" },
  { t: "Este acuerdo está en vigor mientras el Cliente utilice el Servicio. Al cesar el uso, ya sea por iniciativa del Cliente o por iniciativa del Encargado, se aplicarán las disposiciones de la sección 4.4 (Eliminación de datos)." },

  { h: "8. Ley aplicable" },
  { t: "Este acuerdo está sujeto a las leyes del Estado de Israel. La jurisdicción exclusiva corresponde a los tribunales competentes de Israel." },

  { t: `Este acuerdo entra en vigor con la aprobación del Usuario al momento del registro en el Servicio. Versión ${DPA_VERSION} — junio de 2026.` },
]
