/* French legal content — AI translation of the Hebrew source, PENDING HUMAN LEGAL REVIEW. Faithful translation; Israeli law governs. Structure mirrors legalContent.js. */
import { PRIVACY_VERSION, DPA_VERSION, TERMS_VERSION } from '../../lib/legal'

export const PRIVACY_META = `Simplicity · Version ${PRIVACY_VERSION} · Bêta · Mis à jour : juin 2026`
export const TERMS_META = `Simplicity · Version ${TERMS_VERSION} · Bêta · Mis à jour : juin 2026`
export const DPA_META = `Accord de traitement des données · Version ${DPA_VERSION} · juin 2026`

export const PRIVACY_BLOCKS = [
  { h: `1. Introduction` },
  { t: `Simplicity (« le Service », « l'Application ») est un Practice OS (système de gestion de cabinet) destiné aux coachs, mentors et thérapeutes. Le Service est exploité par Benaya Dor (« nous », « l'exploitant »).` },
  { t: `La présente politique de confidentialité explique quelles données sont collectées, comment elles sont traitées et stockées, quels sont vos droits, et comment nous contacter. Cette politique a été rédigée conformément à la loi sur la protection de la vie privée, 5741-1981 et à ses règlements (y compris l'amendement 13), ainsi qu'au RGPD dans la mesure où il est pertinent.` },
  { t: `L'utilisation du Service constitue une acceptation des conditions détaillées dans la présente politique. Si vous n'êtes pas d'accord, veuillez cesser d'utiliser le Service.` },

  { h: `2. Définitions clés` },
  { t: `Utilisateur — un coach, mentor ou thérapeute qui s'inscrit au Service et l'utilise pour gérer son cabinet.` },
  { t: `Client final — la personne accompagnée par l'Utilisateur, et dont les informations sont saisies dans l'Application par l'Utilisateur. Le client final n'est pas une partie directe à l'accord avec Simplicity.` },
  { t: `Données de l'Utilisateur — toute information créée, saisie ou synchronisée vers le Service par l'Utilisateur.` },
  { t: `Exploitant — Benaya Dor, exploitant exonéré (עוסק פטור, un statut fiscal israélien pour petites entreprises), Israël. Courriel : simplicity.os.app@gmail.com` },

  { h: `3. Relation entre les parties — Controller et Processor` },
  { t: `À l'égard des données des clients finals : l'Utilisateur est « le responsable du traitement (Controller) » — il est l'entité qui décide quoi collecter et pourquoi. Simplicity est « sous-traitant (Processor) » — elle traite les données conformément aux seules instructions de l'Utilisateur et aux fins de la fourniture du Service.` },
  { t: `À l'égard des données de l'Utilisateur lui-même (compte, profil, données d'utilisation) : Simplicity est le responsable du traitement (Controller).` },
  { t: `La responsabilité d'obtenir les consentements éclairés des clients finals, de la licéité de la collecte des informations les concernant et de leur fiabilité, incombe entièrement et exclusivement à l'Utilisateur professionnel. L'exploitant n'assumera aucune responsabilité envers des tiers dont les données ont été saisies dans le système par l'Utilisateur.` },

  { h: `4. Données collectées` },
  { h2: `4.1 Données de l'Utilisateur` },
  { t: `Nom complet, adresse de courriel, mot de passe chiffré (ou authentification Google) — lors de l'inscription.` },
  { t: `Profession/fonction — pour la personnalisation de l'interface.` },
  { t: `Données d'utilisation — activité générale aux fins de l'exploitation et de l'amélioration du Service.` },
  { h2: `4.2 Données des clients finals (saisies par l'Utilisateur)` },
  { t: `L'Utilisateur saisit manuellement des données sur ses clients finals. Ces données peuvent inclure :` },
  { t: `Nom complet, téléphone, adresse de courriel.` },
  { t: `Notes, comptes rendus de séances et réflexions — ceux-ci peuvent contenir des informations sensibles.` },
  { t: `Données financières — coût par séance, historique des paiements.` },
  { t: `Ces données sont stockées sur des serveurs de l'Union européenne, isolées pour chaque Utilisateur séparément (Row-Level Security — chaque Utilisateur n'accède qu'à ses propres données), et protégées par un chiffrement au stockage au niveau de l'infrastructure (at-rest) et par un chiffrement en transit (HTTPS/TLS). Il existe un accès technique limité à l'infrastructure aux seules fins d'exploitation, de support et de sauvegarde.` },
  { h2: `4.3 Synchronisation Google Calendar (optionnelle)` },
  { t: `Si l'Utilisateur choisit de connecter son agenda Google, l'Application demande un accès en lecture seule (calendar.readonly) à l'agenda principal. Sont conservés : le titre de l'événement, l'heure de début et de fin, la durée. Ne sont pas conservés : la description, la liste des participants, le lieu.` },
  { t: `Les jetons d'accès à l'agenda sont conservés de manière sécurisée et limités au seul accès du système. Il est possible de déconnecter l'agenda à tout moment — la déconnexion annule l'autorisation d'accès auprès de Google.` },
  { h2: `4.4 Informations techniques et identifiants numériques (amendement 13)` },
  { t: `Conformément à l'amendement 13 de la loi sur la protection de la vie privée, les informations techniques telles que l'adresse IP, les données de localisation et les identifiants numériques sont considérées comme des informations personnelles à tous égards, et nous les traitons avec le niveau de sécurité et de confidentialité requis. Ce type d'information est collecté de manière restreinte aux seules fins de l'exploitation et de la sécurité du Service.` },
  { h2: `4.5 Caractère volontaire de la communication des informations` },
  { t: `Aucune obligation légale ne vous impose de communiquer ces informations ; leur communication se fait de votre plein gré et avec votre consentement, aux fins détaillées à la section 5. Toutefois, sans les informations indispensables (telles que le nom et le courriel lors de l'inscription), nous ne pourrons pas fournir le Service.` },

  { h: `5. Comment les données sont utilisées` },
  { t: `Fourniture du Service — gestion des clients, des séances, des finances et des objectifs pour l'Utilisateur.` },
  { t: `Amélioration du Service — analyse de schémas d'utilisation anonymes aux fins du développement.` },
  { t: `Support technique — traitement des demandes et des incidents.` },
  { t: `Sécurité — détection d'usages abusifs et prévention de tout accès non autorisé.` },
  { t: `Simplicity ne vend pas de données et ne les partage pas avec des acteurs publicitaires. Nous n'utilisons pas d'informations personnelles pour entraîner des modèles d'intelligence artificielle, et nous n'utilisons pas le contenu des notes, des comptes rendus ou des données des clients finals pour entraîner des modèles de quelque type que ce soit.` },

  { h: `6. Stockage et sécurité des données` },
  { h2: `6.1 Lieu de stockage` },
  { t: `Les données du Service sont stockées sur des serveurs Supabase en Irlande (région eu-west-1), dans le domaine de l'Union européenne, conformément au RGPD.` },
  { h2: `6.2 Chiffrement` },
  { t: `Les données sont chiffrées au stockage (at-rest) au niveau de l'infrastructure du fournisseur d'hébergement (Supabase), et isolées pour chaque Utilisateur au moyen de Row-Level Security — de sorte que chaque Utilisateur n'accède qu'à ses propres données.` },
  { t: `Toutes les communications entre l'Application et le serveur sont chiffrées avec le protocole HTTPS/TLS.` },
  { t: `Les mots de passe des Utilisateurs ne sont conservés que sous forme de hash (et non en texte clair).` },
  { h2: `6.3 Accès interne` },
  { t: `L'équipe de Simplicity dispose d'un accès technique limité à l'infrastructure des données aux fins d'exploitation, de support et de sauvegarde, restreint aux seules personnes autorisées. Nous ne vendons pas de données, nous ne les partageons pas avec des annonceurs, et nous n'utilisons pas le contenu des notes pour entraîner des modèles (voir section 5).` },
  { h2: `6.4 Niveau de sécurité et gestion de la protection de la vie privée` },
  { t: `Le Service met en œuvre des mesures de sécurité conformément au règlement sur la protection de la vie privée (sécurité de l'information), 5777-2017, à un niveau de sécurité intermédiaire (niveau 3) : procédures de mots de passe complexes et gestion des autorisations, enregistrement et suivi des accès à la base de données (Logs), et audits de sécurité périodiques.` },
  { t: `Un délégué à la protection des données (DPO) responsable des questions de protection de la vie privée au sein de l'organisation a été désigné ; il est possible de le contacter à l'adresse simplicity.os.app@gmail.com.` },
  { h2: `6.5 Prestataires de services tiers` },
  { t: `Simplicity utilise les prestataires de services suivants pour le fonctionnement du Service :` },
  { t: `Supabase (Irlande) — base de données et authentification des Utilisateurs.` },
  { t: `Vercel (États-Unis) — hébergement de l'interface utilisateur. Peut traiter des données IP et des journaux.` },
  { t: `Google (États-Unis) — authentification OAuth et synchronisation de l'agenda, sous réserve de la politique de confidentialité de Google.` },
  { t: `Resend (États-Unis) — envoi de courriels depuis le système.` },
  { t: `Analytique — futur : sera ajoutée lors de l'activation d'un service d'analytique. Aujourd'hui, nous n'utilisons aucun outil d'analytique tiers.` },
  { t: `Ces prestataires sont soumis à des accords de traitement des données (DPA) appropriés. Les informations qui leur sont transmises le sont, dans la mesure du possible, de manière anonyme ou codée.` },

  { h: `7. Transfert international d'informations` },
  { t: `Certains de nos prestataires de services sont situés hors d'Israël (tels que Vercel et Google aux États-Unis). Le transfert d'informations vers les pays de l'Union européenne et depuis ceux-ci s'effectue conformément à la décision d'adéquation (Adequacy Decision) accordée à Israël.` },
  { t: `Lors d'un transfert vers des pays ne disposant pas d'un niveau de protection adéquat, nous garantissons que le transfert s'effectue au moyen d'un mécanisme juridique approprié — clauses contractuelles types (CCT), consentement explicite de la personne concernée, ou engagement contractuel du destinataire de respecter les standards de la protection de la vie privée israélienne.` },

  { h: `8. Conservation et suppression des données` },
  { h2: `8.1 Tant que le compte est actif` },
  { t: `Les données sont conservées tant que le compte est actif, aux fins de la fourniture du Service.` },
  { h2: `8.2 Suppression du compte` },
  { t: `L'Utilisateur peut supprimer son compte à tout moment depuis les paramètres de l'Application. Après une demande de suppression :` },
  { t: `Il est possible d'annuler la demande dans un délai de 30 jours.` },
  { t: `Au-delà de 30 jours — toutes les données sont supprimées définitivement, y compris les données des clients finals, les séances, les notes et les fichiers.` },
  { t: `Il n'est pas possible de récupérer les données après la suppression définitive.` },
  { h2: `8.3 Exportation des données` },
  { t: `L'Utilisateur peut exporter l'ensemble de ses données à tout moment depuis les paramètres de l'Application, au format Excel. L'exportation comprend : clients, séances, notes, transactions, objectifs et réponses quotidiennes — selon le choix de l'Utilisateur.` },

  { h: `9. Droits de l'Utilisateur` },
  { t: `Conformément à la loi sur la protection de la vie privée (1981) et au RGPD, l'Utilisateur dispose des droits suivants :` },
  { t: `Consultation (article 13 de la loi) — demander à voir quelles données sont conservées à son sujet.` },
  { t: `Rectification (article 14 de la loi) — exiger la rectification d'une information erronée, incomplète ou non à jour.` },
  { t: `Suppression / droit à l'oubli — exiger la suppression des données (voir section 8.2), sous réserve des exceptions prévues par la loi.` },
  { t: `Portabilité — exporter les données dans un format structuré et lisible par machine (voir section 8.3).` },
  { t: `Opposition — s'opposer au traitement des données à des fins de marketing direct ou dans certains autres cas.` },
  { t: `Prévention du courrier indésirable (article 30A de la loi sur les communications) — un envoi publicitaire ne sera adressé que sous réserve d'un consentement explicite ; il est possible de se désinscrire de la liste de diffusion à tout moment, sans frais, au moyen du lien de désinscription au bas de chaque message ou en s'adressant à simplicity.os.app@gmail.com.` },
  { t: `Pour exercer ces droits : simplicity.os.app@gmail.com — nous répondrons dans un délai de 30 jours. Afin de protéger les informations, nous vérifierons l'identité du demandeur avant toute communication, rectification ou suppression de données.` },

  { h: `10. Utilisation des données à des fins de marketing` },
  { t: `Sous réserve d'un consentement explicite lors de l'inscription, nous pouvons utiliser l'adresse de courriel de l'Utilisateur pour créer des audiences publicitaires personnalisées (telles que les Lookalike Audiences) sur des plateformes comme Meta, afin d'élargir la base d'Utilisateurs de Simplicity.` },
  { t: `Cette utilisation : est subordonnée à un consentement explicite uniquement — elle n'est pas cochée par défaut lors de l'inscription. Est limitée au seul courriel de l'Utilisateur — pas aux données des clients finals, pas aux notes, pas au contenu. Peut être annulée à tout moment — en s'adressant à simplicity.os.app@gmail.com.` },
  { t: `Un Utilisateur qui n'a pas consenti ne sera inclus dans aucune action marketing de ce type.` },

  { h: `11. Cookies et suivi` },
  { t: `L'Application utilise des cookies techniques nécessaires à son fonctionnement (conservation de l'état de connexion). Ces cookies sont exemptés de consentement.` },
  { t: `Sous réserve de votre consentement — donné via la bannière de cookies du site — nous pouvons également utiliser des cookies d'analyse et de publicité, y compris des cookies destinés à mesurer l'utilisation, afficher des publicités pertinentes et effectuer du reciblage (retargeting) des visiteurs de la page d'accueil. Ces cookies non essentiels ne sont pas chargés tant que vous n'avez pas consenti, et vous pouvez les refuser ou retirer votre consentement à tout moment via la bannière.` },
  { t: `Les polices de caractères de l'Application sont chargées depuis Google Fonts — cette opération expose l'adresse IP de l'Utilisateur aux serveurs de Google. Aucune information supplémentaire n'est collectée.` },

  { h: `12. Notification d'un incident de sécurité` },
  { t: `Conformément au règlement sur la protection de la vie privée (sécurité de l'information), 5777-2017, en cas d'incident de sécurité grave susceptible de porter une atteinte réelle à la vie privée, nous le signalerons à l'Autorité de protection de la vie privée sans délai, et nous en informerons les personnes concernées affectées dans la mesure où l'incident est susceptible de leur causer un préjudice réel.` },
  { t: `À l'égard des données des clients finals, nous informerons l'Utilisateur (le responsable du traitement) dans un délai de 72 heures à compter de la découverte de l'incident, par courriel à l'adresse enregistrée dans le compte. La notification comprendra la nature de l'incident, le type d'informations exposées, les risques potentiels et les mesures de protection recommandées.` },

  { h: `13. Mineurs` },
  { t: `Le Service est destiné à des professionnels adultes. Il est interdit d'utiliser le Service si l'âge de l'Utilisateur est inférieur à 18 ans. Nous ne collectons pas sciemment de données de mineurs. Si nous en avons connaissance — les données seront supprimées.` },

  { h: `14. Modifications de la politique` },
  { t: `Nous pouvons mettre à jour la présente politique de temps à autre. En cas de modifications substantielles, il sera demandé à l'Utilisateur d'approuver la politique mise à jour lors de sa prochaine connexion à l'Application avant de pouvoir continuer à utiliser le Service.` },

  { h: `15. Gestion de la protection de la vie privée et contact` },
  { t: `Pour toute question, demande ou requête en matière de confidentialité :` },
  { t: `Courriel : simplicity.os.app@gmail.com` },
  { t: `Pour les requêtes en matière de protection de la vie privée, il est également possible de s'adresser à notre délégué à la protection des données (DPO) à l'adresse de courriel ci-dessus.` },
  { t: `Nous répondrons dans un délai raisonnable — jusqu'à 30 jours, conformément aux exigences de la loi.` },

  { t: `La présente politique entre en vigueur à compter de sa publication. Version ${PRIVACY_VERSION} — Bêta.` },
]

export const TERMS_BLOCKS = [
  { h: `1. Acceptation des conditions` },
  { t: `L'utilisation du Service Simplicity (« le Service ») constitue une acceptation pleine, éclairée et irrévocable des conditions détaillées dans le présent document. Si vous n'êtes pas d'accord, veuillez cesser d'utiliser le Service.` },
  { t: `Le Service est exploité par Benaya Dor, exploitant exonéré (עוסק פטור, un statut fiscal israélien pour petites entreprises), Israël (« nous », « l'exploitant »).` },

  { h: `2. Définition du Service` },
  { t: `Simplicity est un Practice OS (système de gestion de cabinet) destiné aux coachs, mentors et thérapeutes. Le Service permet la gestion des clients, des séances, des finances, des objectifs et la synchronisation de l'agenda.` },
  { t: `Le Service est fourni « tel quel » (AS IS) pendant la période de bêta, sans engagement de disponibilité totale ni de fonctionnalités spécifiques.` },

  { h: `3. Inscription et compte` },
  { t: `Vous devez être âgé de 18 ans ou plus pour utiliser le Service.` },
  { t: `Vous êtes responsable de la conservation des identifiants d'accès à votre compte et de toute activité effectuée sous celui-ci.` },
  { t: `Il convient de fournir des informations exactes et à jour lors de l'inscription.` },

  { h: `4. Usage autorisé et interdit` },
  { t: `Autorisé :` },
  { t: `Gérer votre cabinet professionnel — clients, séances, finances.` },
  { t: `Importer vos données existantes.` },
  { t: `Exporter vos données à tout moment.` },
  { t: `Interdit :` },
  { t: `Utiliser le Service à des fins illégales.` },
  { t: `Téléverser un contenu offensant, trompeur, ou portant atteinte aux droits de tiers.` },
  { t: `Tenter de pirater, de perturber, ou d'accéder aux données d'autres Utilisateurs, ou de contourner des mesures de sécurité.` },
  { t: `Utiliser des bots, des robots d'exploration (Crawlers/Spiders) ou des outils automatisés d'extraction d'informations (Data Mining) ou de récupération de données depuis le Service.` },
  { t: `Utiliser les contenus du Service ou ses données pour entraîner des modèles d'intelligence artificielle (Machine Learning/LLM) sans autorisation écrite explicite.` },
  { t: `Faire un usage commercial du Service au-delà de la gestion de votre cabinet personnel — sans accord distinct.` },
  { t: `Transférer le compte à un tiers.` },

  { h: `5. Paiement et abonnement` },
  { t: `Pendant la période de bêta, le Service est fourni gratuitement aux Utilisateurs invités.` },
  { t: `Lors du lancement d'une version commerciale :` },
  { t: `La tarification sera publiée à l'avance dans l'Application.` },
  { t: `Un préavis d'au moins 30 jours sera donné avant l'entrée en vigueur de toute facturation.` },
  { t: `Le non-paiement peut entraîner la suspension de l'accès au Service. Les données seront conservées pendant 60 jours à compter de la date de suspension.` },
  { t: `Annulations et remboursements — toute demande d'annulation d'une opération sera traitée conformément aux dispositions de la loi, y compris la loi sur la protection du consommateur, 5741-1981 et ses règlements. Aucun remboursement n'est accordé pour des périodes d'utilisation déjà facturées, sauf en cas de défaillance substantielle de la part de l'exploitant ou tel que requis par la loi.` },
  { t: `Lors de la facturation, un reçu numérique et un document électronique conforme à la loi seront émis pour documenter l'opération, conformément à l'amendement 73 de la loi sur la protection du consommateur.` },

  { h: `6. Propriété intellectuelle` },
  { t: `L'ensemble du code, du design, du logo et du contenu de Simplicity sont la propriété de l'exploitant.` },
  { t: `Les données que vous saisissez dans le Service sont entièrement les vôtres — nous n'acquérons aucun droit sur celles-ci.` },
  { t: `Vous n'êtes pas autorisé à copier, reproduire ou distribuer des parties du Service sans autorisation écrite.` },
  { t: `Retours et suggestions d'amélioration — tout retour, commentaire, idée ou suggestion d'amélioration que vous nous transmettez en lien avec le Service deviendra la propriété de l'exploitant, et celui-ci sera autorisé à en faire tout usage (y compris leur intégration dans des versions futures) sans contrepartie ni crédit.` },

  { h: `7. Limitation de responsabilité et indemnisation` },
  { t: `Le Service, les interfaces et les intégrations sont fournis « tels quels » (AS IS / AS AVAILABLE), sans engagement de disponibilité continue ni d'intégrité des données. L'exploitant déploie des efforts raisonnables pour un fonctionnement correct mais ne garantit pas que le Service sera exempt de défaillances.` },
  { t: `L'Utilisateur a conscience des risques propres à un Service de ce type :` },
  { t: `Interruptions (Downtime) planifiées et non planifiées ; aucune garantie de disponibilité totale.` },
  { t: `Perte de données ou atteinte à leur intégrité à la suite de défaillances techniques ; il incombe à l'Utilisateur d'effectuer des sauvegardes périodiques.` },
  { t: `Modifications des interfaces API, des fonctionnalités ou des intégrations, qui peuvent être effectuées sans préavis.` },
  { t: `Défaillances des services tiers sur lesquels repose le Service (fournisseurs d'infrastructure, Google, etc.).` },
  { t: `Malgré des mesures de sécurité raisonnables, il n'existe aucune garantie absolue contre les intrusions cybernétiques ou les accès non autorisés.` },
  { t: `Plafond de responsabilité — la responsabilité globale de l'exploitant envers l'Utilisateur au titre de dommages directs prouvés n'excédera pas le montant payé par l'Utilisateur au cours des 12 mois ayant précédé l'événement, ou ₪2,000, selon le montant le plus élevé.` },
  { t: `Cette limitation ne s'appliquera pas aux dommages corporels ou au décès résultant d'une négligence, à la violation d'une obligation de confidentialité de la part de l'exploitant, à un acte intentionnel ou à une négligence grave, ou à d'autres dommages dont la loi n'autorise pas la limitation de responsabilité.` },
  { t: `Indemnisation — l'Utilisateur s'engage à indemniser l'exploitant pour tout dommage ou dépense raisonnable (y compris des honoraires d'avocat raisonnables) qui lui seraient causés en raison d'une violation fondamentale des présentes conditions par l'Utilisateur ou en raison d'un usage illégal du Service.` },

  { h: `8. Suspension et suppression du compte` },
  { t: `L'exploitant est en droit de suspendre ou de supprimer un compte qui enfreint les présentes conditions, sans préavis dans les cas graves (tels qu'une violation grave, une falsification, une atteinte à la sécurité ou une exigence légale immédiate).` },
  { t: `Dans les cas ordinaires — un préavis de 7 jours sera donné avant la suspension, avec la possibilité de contester par courriel.` },
  { t: `L'Utilisateur peut supprimer son compte à tout moment depuis les paramètres de l'Application.` },

  { h: `9. Modifications des conditions` },
  { t: `Nous informerons des modifications substantielles des conditions d'utilisation au moyen d'une notification bien visible dans l'Application et/ou d'une notification à l'adresse de courriel de l'Utilisateur, au moins 30 jours à l'avance. La poursuite de l'utilisation après l'entrée en vigueur des modifications constitue une acceptation.` },
  { t: `Un Utilisateur qui n'accepte pas une modification substantielle est en droit de cesser d'utiliser le Service et de demander la clôture de son compte avant la date d'entrée en vigueur des modifications.` },

  { h: `10. Droit applicable et compétence juridictionnelle` },
  { t: `Les présentes conditions sont soumises au droit de l'État d'Israël. La compétence juridictionnelle exclusive — les tribunaux compétents du district de Tel Aviv-Yafo.` },

  { h: `11. Règlement des litiges` },
  { t: `Démarche initiale — en cas de tout différend ou plainte, veuillez nous contacter d'abord à l'adresse simplicity.os.app@gmail.com afin de tenter de résoudre la question à l'amiable.` },
  { t: `Arbitrage — si le différend n'est pas réglé dans un délai de 30 jours à compter de la démarche initiale, le différend sera tranché par un arbitre unique désigné d'un commun accord par les parties. La procédure d'arbitrage sera confidentielle, et la présente clause constitue une convention d'arbitrage au sens de la loi sur l'arbitrage, 5728-1968. Rien de ce qui précède n'empêche de saisir le tribunal des petites créances, ou de demander des mesures provisoires au tribunal compétent.` },
  { t: `Renonciation à l'action collective — l'Utilisateur accepte de régler tout différend de manière individuelle uniquement, et renonce à son droit de participer à une action collective contre l'exploitant, dans la mesure où la loi le permet.` },

  { h: `12. Force majeure` },
  { t: `L'exploitant n'assumera aucune responsabilité pour l'inexécution ou le retard dans l'exécution de ses obligations résultant de circonstances échappant à son contrôle raisonnable, y compris la guerre, les actes de terrorisme, l'état d'urgence, une pandémie, une catastrophe naturelle, une grève, des défaillances des infrastructures de communication/d'électricité/d'Internet, ou des ordonnances et directives réglementaires imprévues. En pareil cas, les délais d'exécution seront reportés en fonction de la durée de l'événement.` },

  { h: `13. Divisibilité des clauses` },
  { t: `S'il est établi par une instance compétente qu'une disposition quelconque des présentes conditions est nulle ou inapplicable, la validité des autres dispositions ne s'en trouvera pas affectée, et la disposition nulle sera remplacée par une disposition valide aussi proche que possible de l'intention initiale des parties.` },

  { h: `14. Dispositions générales et cession de droits` },
  { t: `Le non-exercice ou le retard dans l'exercice d'un droit de l'exploitant ne sera pas considéré comme une renonciation à ce droit (No Waiver).` },
  { t: `L'exploitant est en droit de céder ses droits et obligations au titre des présentes conditions à un tiers, sous réserve d'un préavis de 30 jours à l'Utilisateur ; l'Utilisateur n'est pas autorisé à céder ses droits sans l'accord préalable et écrit de l'exploitant.` },

  { h: `15. Contact` },
  { t: `Courriel : simplicity.os.app@gmail.com` },
  { t: `Nous répondrons dans un délai de 14 jours ouvrables.` },

  { t: `Les présentes conditions entrent en vigueur à compter de leur publication. Version ${TERMS_VERSION} — Bêta.` },
]

export const DPA_BLOCKS = [
  { h: `1. Les parties` },
  { t: `Le présent accord est conclu entre :` },
  { t: `Le sous-traitant (Processor) : Benaya Dor, exploitant exonéré (עוסק פטור, un statut fiscal israélien pour petites entreprises), exploitant du Service Simplicity (« le sous-traitant »).` },
  { t: `Le responsable du traitement (Controller) : l'Utilisateur inscrit au Service — coach, mentor ou thérapeute (« le Client »).` },
  { t: `Le présent accord régit les conditions de traitement des données des clients finals du Client par le sous-traitant, conformément à la loi sur la protection de la vie privée, 5741-1981 et à ses règlements (y compris l'amendement 13 et le règlement sur la protection de la vie privée (sécurité de l'information), 5777-2017), et conformément au RGPD dans la mesure où il est pertinent.` },

  { h: `2. Définitions` },
  { t: `Données des clients finals — toute information personnelle saisie dans le Service par le Client au sujet des personnes qu'il accompagne, y compris les noms, les coordonnées, les notes de séances et les comptes rendus.` },
  { t: `Traitement — toute opération effectuée sur les données : collecte, stockage, modification, consultation, suppression.` },
  { t: `Violation de sécurité — accès non autorisé, perte, divulgation ou modification de données personnelles.` },
  { t: `Sous-traitant ultérieur (fournisseur secondaire) — un tiers qui traite des données des clients finals pour le compte du sous-traitant aux fins de la fourniture du Service (voir section 4.2).` },

  { h: `3. Finalité du traitement` },
  { t: `Le sous-traitant traite les données des clients finals exclusivement aux fins suivantes :` },
  { t: `Fournir le service de gestion de cabinet au Client (gestion des clients, des séances, des finances, des objectifs).` },
  { t: `Exploitation technique, sauvegardes et sécurité du système.` },
  { t: `Support technique pour les demandes du Client.` },
  { t: `Le sous-traitant ne traitera pas les données des clients finals à toute autre fin, y compris la publicité ou la recherche, sans consentement explicite. En tout état de cause, le sous-traitant n'utilise pas les données des clients finals pour entraîner des modèles d'intelligence artificielle de quelque type que ce soit.` },

  { h: `4. Engagements du sous-traitant` },
  { h2: `4.1 Sécurité de l'information` },
  { t: `Stockage des données sur des serveurs Supabase en Irlande (UE), chiffrées au stockage (at-rest) au niveau de l'infrastructure et en transit (HTTPS/TLS).` },
  { t: `Chiffrement de toutes les communications avec le protocole HTTPS/TLS.` },
  { t: `Limitation de l'accès interne aux données sur la base du principe du besoin d'en connaître (need-to-know).` },
  { t: `Isolement des données pour chaque Utilisateur séparément (Row-Level Security) — chaque Utilisateur n'accède qu'à ses propres données ; l'accès de l'équipe à l'infrastructure est limité aux personnes autorisées aux fins d'exploitation, de support et de sauvegarde.` },
  { t: `Les mesures de sécurité sont mises en œuvre conformément au règlement sur la protection de la vie privée (sécurité de l'information), 5777-2017, à un niveau de sécurité intermédiaire (niveau 3) : procédures de mots de passe et d'autorisations, enregistrement et suivi des accès (Logs) et audits périodiques. Un délégué à la protection des données (DPO) a été désigné.` },
  { h2: `4.2 Fournisseurs secondaires` },
  { t: `Le sous-traitant utilise les fournisseurs secondaires suivants aux fins de la fourniture du Service :` },
  { t: `Supabase (Irlande) — stockage des données.` },
  { t: `Vercel (États-Unis) — hébergement de l'interface utilisateur.` },
  { t: `Google (États-Unis) — authentification et agenda.` },
  { t: `Resend (États-Unis) — courriel.` },
  { t: `Tous les fournisseurs secondaires sont soumis à des accords de traitement des données (DPA) appropriés, qui les obligent à un niveau de protection similaire à celui du présent accord. Le sous-traitant informera le Client de l'ajout ou du remplacement substantiel d'un fournisseur secondaire, et ne transférera pas de données des clients finals à un sous-traitant ultérieur qui ne serait pas soumis à ces engagements.` },
  { h2: `4.3 Violation de sécurité` },
  { t: `En cas de violation de sécurité affectant les données des clients finals, le sous-traitant en informera le Client dans un délai de 72 heures à compter de la découverte, par courriel à l'adresse enregistrée dans le compte. La notification comprendra la nature de l'incident, le type d'informations exposées et les mesures prises.` },
  { t: `En cas d'incident de sécurité grave, le sous-traitant en informera également l'Autorité de protection de la vie privée comme l'exige la loi, et assistera le Client dans l'accomplissement des obligations de notification qui lui incombent en tant que responsable du traitement.` },
  { h2: `4.4 Suppression des données` },
  { t: `Lors de la suppression du compte du Client, toutes les données des clients finals seront supprimées définitivement dans un délai de 30 jours. Aucune copie ne subsistera, hormis les sauvegardes techniques qui seront elles aussi supprimées dans un délai de 90 jours supplémentaires.` },
  { h2: `4.5 Assistance au responsable du traitement` },
  { t: `Le sous-traitant assistera le Client, dans une mesure raisonnable, pour répondre aux demandes des clients finals visant à exercer leurs droits (consultation, rectification, suppression, portabilité), et pour le respect des obligations du Client en vertu de la loi.` },
  { h2: `4.6 Transfert international` },
  { t: `Dans la mesure où le traitement des données implique un transfert hors d'Israël (tel que des fournisseurs secondaires aux États-Unis), le transfert s'effectuera sous réserve d'un mécanisme juridique approprié — décision d'adéquation, clauses contractuelles types (CCT) ou engagement contractuel équivalent.` },
  { h2: `4.7 Confidentialité` },
  { t: `Le sous-traitant garantit que les personnes autorisées agissant pour son compte, qui accèdent aux données des clients finals, sont tenues à une obligation de confidentialité.` },

  { h: `5. Engagements du Client` },
  { t: `Le Client déclare qu'il dispose d'une base légale pour la collecte et le traitement des données de ses clients finals.` },
  { t: `Le Client est responsable d'obtenir les consentements requis de ses clients finals pour le stockage d'informations les concernant.` },
  { t: `Le Client est responsable de l'exactitude des informations qu'il saisit dans le système.` },
  { t: `Le Client ne saisira pas dans le système de données particulièrement sensibles (telles que des numéros d'identité, des données médicales diagnostiquées) au-delà de ce qui est nécessaire à la gestion du cabinet.` },

  { h: `6. Droits du Client` },
  { t: `Demander une liste de toutes les données des clients finals stockées en son nom.` },
  { t: `Exporter l'ensemble des données à tout moment dans un format structuré.` },
  { t: `Exiger la suppression de données spécifiques.` },
  { t: `Recevoir une notification dans un délai de 72 heures de toute violation de sécurité.` },
  { t: `Pour exercer ces droits : simplicity.os.app@gmail.com` },

  { h: `7. Durée et résiliation` },
  { t: `Le présent accord est en vigueur tant que le Client utilise le Service. À la fin de l'utilisation — que ce soit à l'initiative du Client ou à l'initiative du sous-traitant — les dispositions de la section 4.4 (Suppression des données) s'appliqueront.` },

  { h: `8. Droit applicable` },
  { t: `Le présent accord est soumis au droit de l'État d'Israël. La compétence juridictionnelle exclusive — les tribunaux compétents en Israël.` },

  { t: `Le présent accord entre en vigueur lors de l'approbation de l'Utilisateur au moment de l'inscription au Service. Version ${DPA_VERSION} — juin 2026.` },
]
