// @simplicity/core — domain (pure business logic, no DOM / React / I/O)
/* Named rather than `export *`: scheduledMeetings also holds toLocalDate and
   the client-status rules, which dates.ts / clients.ts already re-export —
   a star here would collide with them. */
export {
  generateScheduledMeetings, staleScheduledMeetingIds,
  zonedParts, zonedTimeToInstant, DEFAULT_TIME_ZONE,
} from './scheduledMeetings'
export * from './paymentPlans'
export * from './subscription'
export * from './recurring'
export * from './calendar'
export * from './dates'
export * from './finance'
export * from './overview'
export * from './leads'
export * from './leadSearch'
export * from './taskPressure'
export * from './clients'
export * from './questionTemplates'
export * from './reports'
export * from './insights'
export * from './moon'
export * from './reminders'
export * from './calendarDuplicates'
export * from './enums'
export * from './invoiceDocs'
export * from './goals'
export * from './home'
export * from './projects'
export * from './settingsTree'
export * from './onboarding'
export * from './setupTasks'
export * from './help'
export * from './multiGender'
export * from './admin'
export * from './passwordStrength'
export * from './authErrors'
export * from './account'
export * from './groupMembership'
export * from './whatsapp'
export * from './legal'
export * from './transactionSearch'
export * from './netChartGeometry'
export * from './investment'
