/* ════════════════════════════════════════════════════════════════
   RECURRING ENGINE — pure functions that compute which pending
   transactions a set of active templates SHOULD have generated by
   today, returning the inserts the caller still owes the DB.

   Idempotent: re-running with the same inputs returns []. A schedule
   row is "owed" only for a period (month / week) after the template's
   newest row that has no row at all — including rows in 'skipped' or
   'confirmed' state (those mean the user already dealt with that
   period). An on_meeting row is owed per meeting.
   ════════════════════════════════════════════════════════════════ */

import { toLocalDate } from './dates'

interface RecurringTemplate {
  id?: string
  active?: boolean
  deleted_at?: string | null
  trigger_type?: string
  cadence_type?: string
  day_of_month?: number | string | null
  day_of_week?: number | null
  until_date?: string | null
  created_at?: string
  client_id?: string | null
  group_id?: string | null
  amount?: number
  type?: string
  desc?: string | null
  project_id?: string | null
  category_id?: string | null
}

interface TransactionRow {
  recurring_id?: string | null
  date: string
  scheduled_meeting_id?: string | null
}

interface ScheduledMeeting {
  id?: string
  subject_type?: string
  subject_id?: string
  status?: string
  scheduled_at?: string | number | Date
}

interface RecurringPayload {
  amount?: number
  type?: string
  desc: string | null
  date: string
  status: 'pending'
  recurring_id?: string
  project_id: string | null
  client_id: string | null
  category_id: string | null
  scheduled_meeting_id?: string | null
}

/* YYYY-MM-DD in local time. Stable string lets us compare dates
   without timezone surprises.
   toLocalDate, not new Date: the existing-row keys are built from the
   date-only `date` column while the due-date keys come from real local
   Dates. Parsing the column as UTC shifts its key back a day west of
   Greenwich, the dedup misses, and the template regenerates a duplicate
   pending transaction on every load. */
export function toDateKey(d: Date | string | number): string {
  const date = toLocalDate(d)
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${dd}`
}

/* Number of days in the (year, month0) calendar month. */
function daysInMonth(year: number, month0: number): number {
  return new Date(year, month0 + 1, 0).getDate()
}

/* For monthly_date templates: first due date in (year, month0) at
   day_of_month, clamped to the last day if the month is shorter
   (so a "31st" template still hits on Feb 28). */
function monthlyDateFor(year: number, month0: number, dayOfMonth: number): Date {
  const clamped = Math.min(dayOfMonth, daysInMonth(year, month0))
  return new Date(year, month0, clamped)
}

/* The cadence period a date belongs to: its calendar month for a monthly
   rule, its Sunday-to-Saturday week for a weekly one. A rule owes ONE row per
   period, so this — not the exact date — is what "already generated" has to
   mean. Keyed by exact date, a row whose date the user edited (paid on the
   3rd, not the 1st) left its slot looking empty and the original came back
   as a second pending row: the same income counted twice. */
function periodKey(cadence: string | undefined, d: Date): string | null {
  if (cadence === 'monthly_date') return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, '0')}`
  if (cadence === 'weekly') return toDateKey(new Date(d.getFullYear(), d.getMonth(), d.getDate() - d.getDay()))
  return null
}

/* Walk through every due date the template should have generated,
   starting from `anchorDate` (the template's NEWEST row, or its creation
   date when it has none — see generateRecurringTransactions) and ending at
   `now`. Each step respects until_date if set. Stays in local time
   throughout: until_date is a date-only column, and reading it as UTC
   dropped its last day west of Greenwich. */
export function* dueDatesForTemplate(
  template: RecurringTemplate,
  anchorDate: Date,
  now: Date,
): Generator<Date, void, unknown> {
  const until = template.until_date ? toLocalDate(template.until_date) : null
  if (template.cadence_type === 'monthly_date') {
    const day = Number(template.day_of_month)
    if (!day) return
    /* Start at the anchor month's day_of_month — including the current
       month's occurrence even when the rule was created AFTER that day
       already passed. The missed occurrence surfaces as a pending tx the
       user still confirms; existingKeys dedups anything already generated. */
    let cursor = monthlyDateFor(anchorDate.getFullYear(), anchorDate.getMonth(), day)
    while (cursor <= now && (!until || cursor <= until)) {
      yield new Date(cursor)
      cursor = monthlyDateFor(cursor.getFullYear(), cursor.getMonth() + 1, day)
    }
  } else if (template.cadence_type === 'weekly') {
    const dow = Number(template.day_of_week)
    if (Number.isNaN(dow) || dow < 0 || dow > 6) return
    const cursor = new Date(anchorDate)
    cursor.setHours(0, 0, 0, 0)
    while (cursor.getDay() !== dow) cursor.setDate(cursor.getDate() + 1)
    while (cursor <= now && (!until || cursor <= until)) {
      yield new Date(cursor)
      cursor.setDate(cursor.getDate() + 7)
    }
  }
}

function payloadFromTemplate(t: RecurringTemplate, dateKey: string, scheduledMeetingId: string | null = null): RecurringPayload {
  return {
    amount: t.amount,
    type: t.type,
    desc: t.desc || null,
    date: dateKey,
    status: 'pending',
    recurring_id: t.id,
    project_id: t.project_id || null,
    client_id: t.client_id || null,
    category_id: t.category_id || null,
    scheduled_meeting_id: scheduledMeetingId,
  }
}

/* Build the list of pending-transaction payloads the DB is missing
   for these templates. Pass the live `transactions` array so we can
   subtract rows that already exist for each (recurring_id, date).
   Handles both trigger modes:
     - 'schedule'   → walks cadence_type day-by-day
     - 'on_meeting' → fires once per non-skipped scheduled_meeting on
                      the linked client_id / group_id
*/
export function generateRecurringTransactions(
  templates: RecurringTemplate[] | null | undefined,
  transactions: TransactionRow[] | null | undefined,
  now: Date = new Date(),
  scheduledMeetings: ScheduledMeeting[] = [],
): RecurringPayload[] {
  const out: RecurringPayload[] = []
  if (!Array.isArray(templates) || !templates.length) return out
  /* De-dup keys from existing rows. Every recurring row keys by date; an
     on_meeting row ALSO keys by its scheduled_meeting_id (link added by
     migration 0094). Checking both means we neither regenerate a paid slot nor
     duplicate a meeting a pre-0094 (date-only) row already covers. */
  const existingKeys = new Set<string>()
  for (const et of transactions || []) {
    if (!et.recurring_id) continue
    existingKeys.add(`d|${et.recurring_id}|${toDateKey(et.date)}`)
    if (et.scheduled_meeting_id) existingKeys.add(`m|${et.recurring_id}|${et.scheduled_meeting_id}`)
  }
  for (const t of templates) {
    if (!t.active) continue
    if (t.deleted_at) continue
    const trigger = t.trigger_type || 'schedule'

    if (trigger === 'on_meeting') {
      /* Fire one pending tx per upcoming/recent meeting on the linked
         subject. Skipped/expired meetings don't produce a tx; the
         widget couples the user's "skip" on a meeting to its tx so
         the user doesn't end up paying for a session that didn't
         happen. */
      let subjectType: string, subjectId: string
      if (t.client_id) { subjectType = 'client'; subjectId = t.client_id }
      else if (t.group_id) { subjectType = 'group'; subjectId = t.group_id }
      else continue
      const relevant = (scheduledMeetings || []).filter(
        (m) =>
          m.subject_type === subjectType &&
          m.subject_id === subjectId &&
          m.status !== 'skipped' &&
          m.status !== 'expired',
      )
      for (const m of relevant) {
        const dateKey = toDateKey(m.scheduled_at as Date | string | number)
        const mk = `m|${t.id}|${m.id}`
        const dk = `d|${t.id}|${dateKey}`
        /* Skip if THIS meeting already has a tx, OR a pre-0094 date-only row
           already covers this date (don't duplicate a legacy payment). Add only
           the meeting key — so a SIBLING meeting the same day still generates. */
        if ((m.id && existingKeys.has(mk)) || existingKeys.has(dk)) continue
        existingKeys.add(mk)
        out.push(payloadFromTemplate(t, dateKey, m.id ?? null))
      }
      continue
    }

    /* Default — schedule cadence.

       The walk starts at the template's NEWEST row, not its earliest. From
       the earliest, every change to a rule re-read its whole history against
       the new settings: moving a monthly rule from the 1st to the 15th found
       every past 15th empty and filled each one with a pending row, and
       switching it to weekly did the same for every week since the first
       payment. Nothing before the newest row can be owed — the user has
       already been through that stretch of the ledger.

       What still backfills: everything AFTER the newest row, which is the
       "away for two months" case this engine exists for. What it costs: a
       row that failed to insert BEHIND a later one that succeeded is never
       looked at again. So callers write rows in the order returned (oldest
       first) and stop a pass at the first failed insert — web
       useRecurringGeneration and the phone's lib/generators both do. */
    const txsForT = (transactions || []).filter((x) => x.recurring_id === t.id)
    let anchor: Date
    if (txsForT.length) {
      const newest = txsForT.reduce((max, x) => {
        const k = toDateKey(x.date)
        return k > max ? k : max
      }, toDateKey(txsForT[0].date))
      anchor = toLocalDate(newest)
    } else {
      anchor = new Date(t.created_at as string)
    }
    anchor.setHours(0, 0, 0, 0)
    const filled = new Set<string>()
    for (const x of txsForT) {
      const pk = periodKey(t.cadence_type, toLocalDate(x.date))
      if (pk) filled.add(pk)
    }
    for (const due of dueDatesForTemplate(t, anchor, now)) {
      const dateKey = toDateKey(due)
      const key = `d|${t.id}|${dateKey}`
      const pk = periodKey(t.cadence_type, due)
      if (existingKeys.has(key) || (pk && filled.has(pk))) continue
      existingKeys.add(key)
      if (pk) filled.add(pk)
      out.push(payloadFromTemplate(t, dateKey))
    }
  }
  return out
}

/* Human-readable cadence summary for cards/lists.
   "כל חודש ב-15" / "כל יום ראשון" / "כל חודש ב-15 · עד 31/12/26". */
const DAY_NAMES_HE = ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת']
export function describeCadence(template: RecurringTemplate | null | undefined): string {
  if (!template) return ''
  if (template.trigger_type === 'on_meeting') return 'בעקבות פגישה'
  let core: string
  if (template.cadence_type === 'monthly_date' && template.day_of_month) {
    core = `כל חודש ב-${template.day_of_month}`
  } else if (template.cadence_type === 'weekly' && template.day_of_week != null) {
    core = `כל יום ${DAY_NAMES_HE[template.day_of_week] || ''}`.trim()
  } else {
    core = 'חוזר'
  }
  if (template.until_date) {
    const d = toLocalDate(template.until_date)
    const dd = String(d.getDate()).padStart(2, '0')
    const mm = String(d.getMonth() + 1).padStart(2, '0')
    const yy = String(d.getFullYear()).slice(2)
    core += ` · עד ${dd}/${mm}/${yy}`
  }
  return core
}
