/* ════════════════════════════════════════════════════════════════
   RECURRING ENGINE — pure functions that compute which pending
   transactions a set of active templates SHOULD have generated by
   today, returning the inserts the caller still owes the DB.

   Idempotent: re-running with the same inputs returns []. A
   transaction is "owed" only when no row exists for that
   (recurring_id, date) — including rows in 'skipped' or 'confirmed'
   state (those mean the user already dealt with that period).
   ════════════════════════════════════════════════════════════════ */

/* YYYY-MM-DD in local time. Stable string lets us compare dates
   without timezone surprises. */
export function toDateKey(d) {
  const date = d instanceof Date ? d : new Date(d)
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const dd = String(date.getDate()).padStart(2, '0')
  return `${y}-${m}-${dd}`
}

/* Number of days in the (year, month0) calendar month. */
function daysInMonth(year, month0) {
  return new Date(year, month0 + 1, 0).getDate()
}

/* For monthly_date templates: first due date in (year, month0) at
   day_of_month, clamped to the last day if the month is shorter
   (so a "31st" template still hits on Feb 28). */
function monthlyDateFor(year, month0, dayOfMonth) {
  const clamped = Math.min(dayOfMonth, daysInMonth(year, month0))
  return new Date(year, month0, clamped)
}

/* Walk through every due date the template should have generated,
   starting from the earliest tx for it (or, if none, from the
   template's creation date) and ending at `now`. Each step respects
   until_date if set. Stays in local time throughout. */
export function* dueDatesForTemplate(template, anchorDate, now) {
  const until = template.until_date ? new Date(template.until_date) : null
  if (template.cadence_type === 'monthly_date') {
    const day = Number(template.day_of_month)
    if (!day) return
    /* Start at the anchor month's day_of_month — including the current
       month's occurrence even when the rule was created AFTER that day
       already passed. The missed occurrence surfaces as a pending tx the
       user still confirms; existingKeys dedups anything already generated. */
    let cursor = monthlyDateFor(anchorDate.getFullYear(), anchorDate.getMonth(), day)
    while (cursor <= now && (!until || cursor <= until)) {
      yield new Date(cursor)
      cursor = monthlyDateFor(cursor.getFullYear(), cursor.getMonth() + 1, day)
    }
  } else if (template.cadence_type === 'weekly') {
    const dow = Number(template.day_of_week)
    if (Number.isNaN(dow) || dow < 0 || dow > 6) return
    const cursor = new Date(anchorDate)
    cursor.setHours(0, 0, 0, 0)
    while (cursor.getDay() !== dow) cursor.setDate(cursor.getDate() + 1)
    while (cursor <= now && (!until || cursor <= until)) {
      yield new Date(cursor)
      cursor.setDate(cursor.getDate() + 7)
    }
  }
}

function payloadFromTemplate(t, dateKey) {
  return {
    amount: t.amount,
    type: t.type,
    desc: t.desc || null,
    date: dateKey,
    status: 'pending',
    recurring_id: t.id,
    project_id: t.project_id || null,
    client_id: t.client_id || null,
    category_id: t.category_id || null,
  }
}

/* Build the list of pending-transaction payloads the DB is missing
   for these templates. Pass the live `transactions` array so we can
   subtract rows that already exist for each (recurring_id, date).
   Handles both trigger modes:
     - 'schedule'   → walks cadence_type day-by-day
     - 'on_meeting' → fires once per non-skipped scheduled_meeting on
                      the linked client_id / group_id
*/
export function generateRecurringTransactions(
  templates,
  transactions,
  now = new Date(),
  scheduledMeetings = [],
) {
  const out = []
  if (!Array.isArray(templates) || !templates.length) return out
  const existingKeys = new Set(
    (transactions || [])
      .filter((t) => t.recurring_id)
      .map((t) => `${t.recurring_id}|${toDateKey(t.date)}`),
  )
  for (const t of templates) {
    if (!t.active) continue
    if (t.deleted_at) continue
    const trigger = t.trigger_type || 'schedule'

    if (trigger === 'on_meeting') {
      /* Fire one pending tx per upcoming/recent meeting on the linked
         subject. Skipped/expired meetings don't produce a tx; the
         widget couples the user's "skip" on a meeting to its tx so
         the user doesn't end up paying for a session that didn't
         happen. */
      let subjectType, subjectId
      if (t.client_id) { subjectType = 'client'; subjectId = t.client_id }
      else if (t.group_id) { subjectType = 'group'; subjectId = t.group_id }
      else continue
      const relevant = (scheduledMeetings || []).filter(
        (m) =>
          m.subject_type === subjectType &&
          m.subject_id === subjectId &&
          m.status !== 'skipped' &&
          m.status !== 'expired',
      )
      for (const m of relevant) {
        const dateKey = toDateKey(m.scheduled_at)
        const key = `${t.id}|${dateKey}`
        if (existingKeys.has(key)) continue
        existingKeys.add(key)
        out.push(payloadFromTemplate(t, dateKey))
      }
      continue
    }

    /* Default — schedule cadence. */
    const txsForT = (transactions || []).filter((x) => x.recurring_id === t.id)
    let anchor
    if (txsForT.length) {
      const earliest = txsForT.reduce((min, x) => (x.date < min ? x.date : min), txsForT[0].date)
      anchor = new Date(earliest)
    } else {
      anchor = new Date(t.created_at)
    }
    anchor.setHours(0, 0, 0, 0)
    for (const due of dueDatesForTemplate(t, anchor, now)) {
      const key = `${t.id}|${toDateKey(due)}`
      if (existingKeys.has(key)) continue
      existingKeys.add(key)
      out.push(payloadFromTemplate(t, toDateKey(due)))
    }
  }
  return out
}

/* Human-readable cadence summary for cards/lists.
   "כל חודש ב-15" / "כל יום ראשון" / "כל חודש ב-15 · עד 31/12/26". */
const DAY_NAMES_HE = ['ראשון', 'שני', 'שלישי', 'רביעי', 'חמישי', 'שישי', 'שבת']
export function describeCadence(template) {
  if (!template) return ''
  if (template.trigger_type === 'on_meeting') return 'בעקבות פגישה'
  let core
  if (template.cadence_type === 'monthly_date' && template.day_of_month) {
    core = `כל חודש ב-${template.day_of_month}`
  } else if (template.cadence_type === 'weekly' && template.day_of_week != null) {
    core = `כל יום ${DAY_NAMES_HE[template.day_of_week] || ''}`.trim()
  } else {
    core = 'חוזר'
  }
  if (template.until_date) {
    const d = new Date(template.until_date)
    const dd = String(d.getDate()).padStart(2, '0')
    const mm = String(d.getMonth() + 1).padStart(2, '0')
    const yy = String(d.getFullYear()).slice(2)
    core += ` · עד ${dd}/${mm}/${yy}`
  }
  return core
}
